### ISSUE TITLE
gf regressions

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1044]
1. `gf` is not mapped with `git rebase -i` currently anymore, likely because the `FileType` autocommand to set it up gets only added when `BufReadPost` initializes fugitive.

2. When using `:e` or `doautocmd FileType` to work around the first issue, it results in `E345: Can't find file "<Plug>5ecc8125" in path`.
`map gf` shows `n  gf          &@<SNR>47_:find <Plug><cfile><CR>`
And the cmap also exists: `c  <Plug><cfile> *@fugitive#Cfile()`.
It looks like the `<cfile>` gets replaced already before?

Tested with both Neovim and Vim, using a minimal vimrc.
With Vim `set filetype=gitcommit` is also required.

**Comment by tpope** [comment]
1. Figured there'd be a few load order issues like this. Simple fix.

2. This has been broken since https://github.com/tpope/vim-fugitive/commit/b1df5f1226676ae52380a214e0b13af1250951cd, which accidentally changed it to a `<script>` map. Missed it because of some shenanigans in my personal config. Dang it, this is big enough that I should probably cut another stable release.
