### ISSUE TITLE
Run alternative command instead of 'git grep'

### ISSUE THREAD

**Issue by systemmonkey42** [tpope/vim-fugitive#1050]
I use silver-searcher (ag) to search my repo because its quick and has support for ignore files

(I know git supports `.gitignore`, but then git *always* ignores the files.  I only want `git grep` to ignore the files)

I have a wrapper "git ag" which takes `git grep` compatible parameters but calls `ag` so I can take advantage of the ignore files (its a very large project, and I'm only interested/working on a small part of it.. Sub-modules are unfortunately not an options for this project. 

I achieved what I needed by modifying the following line in Ggrep;
```
let &grepprg = s:repo().git_command('--no-pager', get(g:,'fugitive_grep_command','grep'), '-n', '--no-color')
```

And in my startup script `let g:fugitive_grep_command='ag'`. 

I'm submitting this in the hope it can become standard. I'm not a fan of maintaining personal forks of everything.

**Comment by tpope** [comment]
I use `ag` from time to time too, but I set it to `'grepprg'` and call it with `:grep`. I don't get what this buys you over that, other than perhaps not having to think about the working directory.  It's otherwise a terrible fit, as `ag` can't grep through old commits, and `:Ggrep` can't take advantage of `ag` features like showing the column. Round peg, square hole.
