### ISSUE TITLE
Feature request: Gadd comand

### ISSUE THREAD

**Issue by chemzqm** [tpope/vim-fugitive#1057]
I would like to use `:Gadd` to add files using vim's command line interface.

**Comment by tpope** [comment]
What would this command do above and beyond `:Gwrite` and `:Git add` cannot?

**Comment by gsauthof** [comment]
> What would this command do above and beyond `:Gwrite` and `:Git add`?

1. It wold be less dangerous than `:Gwrite` - e.g. when I do `:Gdiff`, then `:q` to close one buffer, and then `:Gw` this results in a checkout of my recently changed file and not in the staging of those recent changes. Thus, my changes are lost.
2. `:Gwrite` always re-writes the file, even if the buffer isn't modified - thus, it may yield some unnecessary compilations in my next `:make` call (think: header which is used by 20 other translation units)
3. It would be less to type, i.e. the `:Git add %` has on overhead of 5 characters
4. It would make the Fugitive command set more self-consistent - I mean most commands are constructed like `G` plus the git command name - e.g. `Gdiff`, `Glog` etc. But when I want to add a file I have to remember that there isn't a `Gadd`. Irritating for new an occasional users of Fugitive.

**Comment by tpope** [comment]
> 1. It wold be less dangerous than `:Gwrite` - e.g. when I do `:Gdiff`, then `:q` to close one buffer, and then `:Gw` this results in a checkout of my recently changed file and not in the staging of those recent changes. Thus, my changes are lost.

Perhaps we should require `!` in this case.

> 2. `:Gwrite` always re-writes the file, even if the buffer isn't modified - thus, it may yield some unnecessary compilations in my next `:make` call (think: header which is used by 20 other translation units)

Sounds like an argument for `:Gupdate`.

> 3. It would be less to type, i.e. the `:Git add %` has on overhead of 5 characters

This feels like the crux of it. On the one hand, I get it, those characters do add up over time. But on the other hand, there are dozens of commands that this is true for (hundreds if you lower the bar to "3 characters"), and I really don't want to open Pandora's box.

> 4. It would make the Fugitive command set more self-consistent - I mean most commands are constructed like `G` plus the git command name - e.g. `Gdiff`, `Glog` etc. But when I want to add a file I have to remember that there isn't a `Gadd`. Irritating for new an occasional users of Fugitive.

Nice try but only a third of commands get their names from Git. And `:Gdiff` is a funny example because I screwed up not naming it `:Gdiffsplit` after the Vim command.

**Comment by krishan** [comment]
For what it's worth: I have also been burnt by `Gwrite` in exactly the way described above (throwing away the changes, instead of preparing them for commit). 

I think it would be nice for fugitive to offer a safer way to "git add current file", without having to worry about inadvertently deleting my work.

**Comment by krishan** [comment]
Cool, thank you 👍

**Comment by tpope** [comment]
I would also like to add (ha ha) that argument semantics of a `:Gadd` command are super unclear: would `:Gadd -p` operate on the current file or all files? I ripped out `:Glog` operating on the current file by default because it was more complicated than it was helpful.

`:G` with arguments is an alias for `:Git` now so that 5 character overhead has been reduced to 3.
