### ISSUE TITLE
Not an editor command :Gblame

### ISSUE THREAD

**Issue by joereynolds** [tpope/vim-fugitive#1066]
Ever since commit https://github.com/tpope/vim-fugitive/commit/4b0475f9d84ab9277c57c354deefb7ce5d2ef6b9 `:Gblame` no longer works, I haven't investigated why but that is the commit causing the issue.

**Comment by barhamd** [comment]
This fixed it for me:
`cd ~/.vim/bundle/vim-fugitive`
`git remote update origin`
`git pull`

**Comment by rodolfobandeira** [comment]
I keep getting the same thing. Here are some details:

MacOS Catalina (10.15.1)

---

`cd ~/.vim/bundle/vim-fugitive; git log -n 1`

```
commit b68b6d4329d9bee58a521e0ff8c6adbbc53915b4 (HEAD -> master, origin/master, origin/HEAD)
Author: Jon Parise <jon@indelible.org>
Date:   Wed Dec 11 14:29:46 2019 -0800

    Mention vim-phabricator for Phabricator browsing
```

---

`git --version`

```
git version 2.24.1
```

---

`vim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 16:52:17)
```

---

Do you guys have any idea how can I debug this?

**Comment by tpope** [comment]
My guess would be you have 2 versions of Fugitive installed and the old one is taking precedence.

**Comment by rodolfobandeira** [comment]
@tpope Where would this second `vim-fugitive` be installed exactly?
Here is more debugging: 

---

`cd ~/.vim;ls`

```
bundle colors
```

`cd ~/.vim/bundle`

`ls -lh | grep vim-fugitive | cut -d ' ' -f7-15`

```
  416B 21 Dec 12:07 vim-fugitive
```

`rm -rf vim-fugitive`

`vim` Starting vim and triggering NeoBundle:

```
Not installed bundles:  ['vim-fugitive']
Install bundles now?
(y)es, [N]o:
```

`Y`

...

Testing again via my custom command:

```
map <Leader>b :<C-U>GBlame<CR>
```

Same error:

```
E492: Not an editor command: GBlame
```

Checking again if the folder exists and was updated:

`ls -lh | grep vim-fugitive | cut -d ' ' -f7-15`

```
  416B 23 Dec 14:28 vim-fugitive
```

**Comment by rodolfobandeira** [comment]
@tpope Looks like using `Gblame` works. Just edited my `.vimrc` to use `Gblame` instead of `GBlame` and everything works. Interesting because it was working before so might be something else that turned to be more "case sensitive". 

Hope this info might be helpful for someone else with the same issue.
Cheers!

**Comment by lumbric** [comment]
If you came here googling for a solution:

Since quite some while, it seems to be `:Git blame` instead of `:Glame`.

(Deprecated since quite some while, I think removed in 3.7: _"Turn remaining deprecated commands (:Gbrowse, etc.) into error stubs."_ from [changelog](https://www.vim.org/scripts/script.php?script_id=2975).)

See 4a24804ad. And a similar [comment here](./1353#issuecomment-1645601610).
