### ISSUE TITLE
Error writing staged changes for Go file introduced in v2.5

### ISSUE THREAD

**Issue by joshuarubin** [tpope/vim-fugitive#1128]
I'm able to write to the git cache for other file types, but I get this error when trying to write a Go file:

```
Error detected while processing BufWriteCmd Autocommands for "fugitive://*//[0-3]/*":
E20: Mark not set
```

Only seems to be an issue in `v2.5`, reverting to `v2.4` fixed things for me.

**Comment by blueyed** [comment]
Can you git-bisect it to a commit between those tags, please?

**Comment by tpope** [comment]
The fact it's limited to one file type makes me think it might be triggered by a ftplugin. I can write to Go files in the index just fine. See if stripping down your config helps.

**Comment by tpope** [comment]
See what the output of `:echo fugitive#BufWriteCmd(@%)` is.

**Comment by washtubs** [comment]
I'm having the exact same issue, so here goes:

I edit /path/to/main.go
:Gdiff
Run the command you posted in the staging buffer
and I'm getting: 

    noautocmd '[,']write fugitive:///path/to/.git//0/main.go

**Comment by tpope** [comment]
Oh, you'll need to run `ggyG` before the `:echo` to force the marks to refer to the full file.

**Comment by washtubs** [comment]
I neglected to mention the staging buffer also gets cleared when I run that command. This doesn't happen for non-go files, and it also doesn't happen when I disable `g:go_fmt_autosave`. The echo command is also otherwise silent.

It doesn't seem to change anything if I yank the whole buffer first. In either case, when I do the echo command, it prints that as output, and it empties the staging buffer.

**Comment by bhcleek** [comment]
@tpope vim-go runs `go fmt <filename>` on a temporary file and then does a [`rename` to move the temporary file](https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim#L108). We might have a more general solution to fix this for vim-go, but since this just crept up from vim-fugitive in v2.5 I thought you might want to know.

**Comment by bhcleek** [comment]
For sure. We're looking at either implementing bailing when the target isn't `filereadable` or implementing a solution that replaces the contents of the buffer directly instead of using `rename`.

**Comment by washtubs** [comment]
With a non-go file, it's the same behavior as when I have the auto format off for a go file. So same test, echo command is silent and it doesn't clear the staging buffer.

**Comment by tad-lispy** [comment]
Same issue with Elm files (with `elm-format`).

**Comment by tpope** [comment]
Looks like this is fixable in the respective formatting plugins, so calling this closed.

P.S. `expand('%@')` is (benignly) wrong. The `@` is ignored so it's equivalent to `expand('%')`. You can also do `@%` *without* the `expand('')`.
