### ISSUE TITLE
:Gbrowse flashing screen but no git output

### ISSUE THREAD

**Issue by eloehr** [tpope/vim-fugitive#1135]
Having trouble getting :Gbrowse to work with fugitive-gitlab.vim.

:Glog works as expected.  But from within a git repo file vim session, :Gbrowse just flashes my terminal back to the shell for a split second, and then returns to the vim session. No sign of any git output.

My config:

.vimrc (with my actual domain replaced with 'mydomain'):
let g:fugitive_gitlab_domains = ['https://git.mydomain.com']

:echo g:fugitive_browse_handlers

yields

[function('gitlab#fugitive_handler')]

This is vim 8.0, git 2.20.1

Ideas?

**Comment by abers** [comment]
Having exact same issue. Got vim-fugitive and vim-rhubarb and running :GBrowse flashes the terminal but otherwise does nothing.

**Comment by tpope** [comment]
Try `call netrw#BrowseX('https://github.com', 0)` and see if that opens the URL in a browser.

**Comment by abers** [comment]
Thanks for the reply. Trying that the exact same thing happens. I am on Kubuntu 19.04 and my terminal is Konsole, if that info is any use to you.

**Comment by tpope** [comment]
For future reference, does `gio open` work with your i3 setup?

**Comment by abers** [comment]
Gio open works, even with konqueror uninstalled.

**Comment by tpope** [comment]
So Fugitive uses netrw for spawning the browser because it's a harder than you would think problem that I frankly don't have the bandwidth to solve. According to the warning message on my system, `xdg-open` is deprecated in favor of `gio open`. I'd recommend notifying the maintainer of this and seeing if he'll consider adding `gio open` as a higher priority alternative.

You can also just override the default locally:

	:let g:netrw_browsex_viewer= "gio open"

**Comment by jbonhag** [comment]
This solved the issue for me on macOS:

```
:let g:netrw_browsex_viewer= "open
```
