### ISSUE TITLE
Change Gstatus order and split untracked and unstaged

### ISSUE THREAD

**Issue by petobens** [tpope/vim-fugitive#1159]
In the recent UI changes you combined unstaged and untracked files and placed the untracked files section at the top of the Gstatus buffer. Personally I prefer the way standard `git status` works: showing staged,unstaged and untracked sections separately (and in that order). I rarely interact with the untracked files so (at least for me) it makes sense to have them at the bottom of the buffer which avoids scrolling and allows to easily move between modified files with `<C-n>` and `<C-p>` mappings. 
What's the rationale for the change? (can it be reverted or made opt-in?)

Bonus: it would also be really nice to have some highlighting for the staged (green) and unstaged  files (red).

**Comment by tpope** [comment]
I borrowed the section order from Magit, where at first I too found it alienating before I started to see the logic in it. It's chronological. Your changes start out at the top in the unstaged section, then they move down into staged, then they're committed and move down into unpushed, where they continue to drop down as more commits are added.

Combining untracked and unstaged was my own idea. In part it was a compromise so that untracked wouldn't be the very first section (a decision I'm now rethinking). Mostly it was just to streamline things, make it easier to move among all your changes and save a couple of display lines to boot.

My answer to "doctor, it hurts when I have untracked files" is "don't have untracked files". This is something I've been guilty of myself, and this `:Gstatus` change forcing me to be more diligent has been a huge win. I no longer forget to add new files I create! Go through that list of untracked files and either track them or add them to `.gitignore` or `.git/info/exclude`. You'll thank me later.

**Comment by petobens** [comment]
Great explanation thanks. I do still believe that the unstaged and untracked sections should be split and that it would be nice to add some coloring. Feel free to close whenever you deem fit.

**Comment by mcepl** [comment]
I agree with you both ;).

1. Colours would be nice. Bright red for untracked files (to show, there is something wrong there), lovely green for the staged ones, and yellow for unstaged? (or whatever the appropriate vim colours are)

2. Adding to ``.gitignore`` is a good idea. Why don't we have it? Suggested UI:
    a. Press a key shortcut (``i``?)
    b. One line textbox opens with the suggested line to be added to ``.gitignore`` file.
    c. Perhaps some switch between ``.gitignore`` (default) and ``.git/info/exclude``?
    d. ``<CR>``

**Comment by emilyst** [comment]
One of the issues with having a UI which adds things to `.gitignore` is that you'd want to be able to _unignore_ things, in case you accidentally trigger it or regret your decision or what have you. (Everything else is reversible, so it would be sensible to make this reversible, too.)

This implies that you'd then have to list the whole `.gitignore` file there in the status menu and then provide programmatic manipulation thereof (which Git doesn't provide, as far as I know, so it'd need to be written).

**Comment by mcepl** [comment]
@emilyst I think that happens rather less than adding new items, so you can just edit ``.gitignore`` directly. Vim is for editing plain text, so you are not against doing that, right?

**Comment by emilyst** [comment]
Doesn't that argument work for not adding a UI for ignoring things in the first place?

**Comment by mcepl** [comment]
@emilyst "happens rather less than"

**Comment by sodapopcan** [comment]
I definitely appreciate unification of untracked and unstaged for the very reason that I frequently forget to add new files.  They are pretty easily distinguished by their "icons", though I'm in agreement that some colour-coding would be nice.  Green/red for staged/unstaged and a totally different colour for untracked?

**Comment by tpope** [comment]
We should work within the confines of the colorscheme, not just pluck colors out of thin air. I might change the leading character from `Type` to `Keyword` or something for the unstaged section. It's a balancing act between informative and busy.

For ignore, I was thinking I might split the difference and have a map that edits the ignore file and adds the filename, but leaves you responsible for writing the file. It could be paired with a map to open the file without adding the line, for the removal use case.

I'm tempted to limit it to `.git/info/exclude` because `.gitignore` is often worth keeping organized, not just blindly appending to the bottom.

**Comment by mcepl** [comment]
Well, then, perhaps slightly lower hanging fruit: on ``I`` open split with ``.gitignore`` (or ``1I`` to open ``.git/info/exclude``), and after saving and closing the split, reload the current status reflecting current ignoring.

**Comment by atondwal** [comment]
hmm, does this just amount to something like `autocmd! BufReadPre,FileReadPre */.git/index nnore <buffer> I yy<Esc>:vsp .git/info/exclude<CR>Gpxx:w<CR>:G<CR>`?

(I know nothing about fugitive's internals, but I'm just going to add that to my vimrc, so I can use it before it gets implemented :) )

**Comment by dsirov** [comment]
> I borrowed the section order from Magit, where at first I too found it alienating before I started to see the logic in it. It's chronological. Your changes start out at the top in the unstaged section, then they move down into staged, then they're committed and move down into unpushed, where they continue to drop down as more commits are added.
> 
> Combining untracked and unstaged was my own idea. In part it was a compromise so that untracked wouldn't be the very first section (a decision I'm now rethinking). Mostly it was just to streamline things, make it easier to move among all your changes and save a couple of display lines to boot.
> 
> My answer to "doctor, it hurts when I have untracked files" is "don't have untracked files". This is something I've been guilty of myself, and this `:Gstatus` change forcing me to be more diligent has been a huge win. I no longer forget to add new files I create! Go through that list of untracked files and either track them or add them to `.gitignore` or `.git/info/exclude`. You'll thank me later.

I understand where you are going with this...
But I guess the most intuitive thing for the UI is to emphasize information according to importance.
And that would be (IMHO):
1. conflicts
2. staged
3. modified
4. untracked

Order is one of the ways to emphasize stuff, we can also consider using color like @petobens suggested.
I do think we better make sure the important things do stand out immediately and I feel that is less so after recent changes...

**Comment by tpope** [comment]
It is very easy to make an argument that unstaged (stuff I'm still working on) is more important than staged (stuff that's ready to go).

**Comment by tpope** [comment]
Update: untracked and unstaged are separate sections again. New `gI` map facilitates ignoring files.

**Comment by petobens** [comment]
> Bonus: it would also be really nice to have some highlighting for the staged (green) and unstaged files (red).

There are no plans for this to happen then?

**Comment by tpope** [comment]
Depends on if you have plans to send a patch!

**Comment by sodapopcan** [comment]
I really want this too.  I usually get used to new functionality within a week, but in this case—and as much as greatly prefer the new `:Gstatus` to the old one—my brain is still, months later, telling me that staged is on top.

@petobens Are you planning on implementing something?

**Comment by tpope** [comment]
*Fine.*

**Comment by petobens** [comment]
Thank you!

**Comment by sodapopcan** [comment]
I asked if someone was working on an implementation as I was taking a stab myself.  Once again, I've learned a bunch from seeing your implementation.  Thank you much!
