### ISSUE TITLE
Stash completion broken in zsh

### ISSUE THREAD

**Issue by rbong** [tpope/vim-fugitive#1226]
When completing `stash`, the ending curly brace is not escaped.
Example: `:Git stash apply stash<Tab>` -> `:Git stash apply stash@\{0}`

This results in zsh being unable to parse the stash:
`zsh: parse error near '}'`

Apparently, by default, zsh treats closing braces as significant even without an opening brace.

Setting the `IGNORE_CLOSE_BRACES` option in zsh and setting `shell` to a value in vim that loads it as a workaround does not appear to work:
```
:Git stash show stash@\{0}
Too many revisions specified: 'stash@{0' '}'
```

You have to disable brace completion entirely with `setopt IGNORE_BRACES`.

**Comment by tpope** [comment]
If you create a file named `stash@{0}`, and then invoke `:!ls stash<Tab>`, the same thing happens. Vim doesn't have special shell completion rules, it just uses its own filename escaping which is similar but not identical to most UNIX shells. Count your lucky stars you're not using `cmd.exe`.

I don't see any downsides to completing this to `stash@{0}` if you want to try to hack that into `s:fnameescape()`. But a filename like `foo{bar,baz}` still needs to complete to `foo\{bar,baz}` because the `{` is operative in that case. Alternatively, `stash@\{0\}` would be uglier but probably easier to implement.

`IGNORE_CLOSE_BRACES` is behaving as documented, it won't help you here.
