### ISSUE TITLE
Feature request: mapping to open the file under the cursor from worktree

### ISSUE THREAD

**Issue by bam80** [tpope/vim-fugitive#1230]
There are Navigation mappings for opening the file, but seems none of them opens a file from worktree.

It would be helpful to directly open the worktree-files from commit buffers, positioning to the needed chunk, if possible.

**Comment by tpope** [comment]
Jumping to the chunk automatically is an awesome if obvious idea, but how do we find the chunk? What happens if it no longer exists?

**Comment by bam80** [comment]
If it no longer exists, we could jump to the latest file version where the chunk exists, or do not jump at all.
How about this?

**Comment by tpope** [comment]
Tell me how to find the latest version of the file where it exists and I'll consider it further.

**Comment by bam80** [comment]
For consistency, maybe for now just ignore such hunks which do not exist any more?

**Comment by tpope** [comment]
Sounds very inconsistent to me.

How do we find the hunk in the work tree version?

**Comment by bam80** [comment]
`git blame` gives info about all the hunks. Can we use that?

**Comment by tpope** [comment]
In blobs, the jump to file `<CR>` map is re-purposed to jump to the diff where the line was added, using `:Gblame` under the hood. I've extended this so that `1<CR>` finds where the line was *removed* using `:Gblame --reverse`, or jump to the line in the work tree version if it still exists. So, this satisfies your request within the bounds of my consistency requirement.

**Comment by bam80** [comment]
@tpope Many thanks!
Could you please link corresponding PR/commit here?
