### ISSUE TITLE
Feature request: try to restore the cursor position when :Gedit swaps the buffers

### ISSUE THREAD

**Issue by bam80** [tpope/vim-fugitive#1231]

**Comment by tpope** [comment]
Try how?

**Comment by bam80** [comment]
Well, at least when the buffers are identical, it's possible to restore position precisely.
Of course, it only makes sense when no position was saved before for that buffer.

**Comment by tpope** [comment]
I've warmed up to this for the zero argument version of `:Gedit`. I think the "how" is answered by `git diff` plus counting offsets from hunks.

**Comment by odnoletkov** [comment]
As a workaround I currently use `:Gdiffsplit` instead of `:Gedit` (with same arguments) when I want to preserve the cursor position. This opens target buffer in a split and – thanks to Vim built-in `diffsplit` logic I believe – the cursor position is preserved. Then I just <kbd>CTRL-W_o</kbd> and I'm good to go.
