### ISSUE TITLE
:Gdiff breaks on symlinked files

### ISSUE THREAD

**Issue by psliwka** [tpope/vim-fugitive#1270]
Steps to reproduce:
```sh
$ cd $(mktemp -d)
$ git init
$ echo "This is sample file content" > file.txt
$ ln -s file.txt symlink.txt
$ git add .
$ git commit -m .
$ vim symlink.txt
:Gdiff
```

Expected result: there is no difference shown, as if one was running `:Gdiff` directly on `file.txt`:
![expected](https://user-images.githubusercontent.com/6830301/60383635-c2b3f180-9a73-11e9-923e-8b4bf153d7b6.png)

Actual result: `:Gdiff` tries to compare symlink target path with symlinked file content:
![actual](https://user-images.githubusercontent.com/6830301/60383769-a6b14f80-9a75-11e9-8529-056e99b65842.png)

**Comment by tpope** [comment]
```
echo "This is another file" > file2.txt
git add .
git commit -m 2
ln -sf file2.txt symlink.txt
```

Now what should `:Gdiff` show?

**Comment by psliwka** [comment]
Good question. Personally, I'd expect to see diff on `file2.txt`, so an empty diff again.

This seems sane behavior to me - the content is what I care about when I'm `:Gdiff`ing currently edited file. The fact that I've opened it through a symlink changes very little.

Showing a diff between target paths would be okay too, but IMHO less expected, and less useful behavior.

**Comment by tpope** [comment]
Your proposal is logically consistent, but is contrary to how Git itself works: `git diff symlink.txt` does *not* show a diff for `file.txt`. The only way for Fugitive to provide your desire is to effectively implement its own symlink handler, which I strongly doubt is feasible once you throw in recursive and directory symlinks.

Fear not though, it sounds like your desire would be effectively addressed by something like https://github.com/aymericbeaumet/symlink.vim (found in #147 but didn't test it).

**Comment by psliwka** [comment]
Thanks, I'll give symlink.vim a try :+1: 

I see your point that my proposal is contrary to what `git diff` works. However, current `:Gdiff` behavior does not resemble `git diff` either.

Right now, `:Gdiff` compares apples to oranges, showing symlink target path in the first pane, and the target file content in the second one. As result, one sees a huge, misleading diff, even if the workdir is completely clean. From my point of view, this is a bug.

@tpope, if comparing file contents as I proposed is not an option, what do you think about showing symlink target paths in both windows in such case? This would at least not show any changes when there are none. Also, it would be fully consistent with `git diff` output.

**Comment by tpope** [comment]
`:Gdiff` opens a second buffer and diffs against it. It doesn't change the first buffer, so your final suggestion is the only thing I would consider "not an option". How would it even work? Editing a temp file?

Having `:Gdiff` compare against the contents of `file.txt` is an *option*, I just question the feasibility. Feel free to prove me wrong! Don't expect any help from Git, basically everything but `git checkout` treats them as just dumb files with paths in them, same as Fugitive.

And lastly, let me let you in on a secret: symlinks suck for anything user facing, doubly so with Git. Even if `:Gdiff` was fixed to your liking, it would be inconsistent with `:Gwrite` and `:Git add %`, because Git doesn't follow the symlink. The correct solution to this broken abstraction is to stop using it!
