### ISSUE TITLE
`:Git log --oneline --decorage --graph --all` stopped showing colours on neovim.

### ISSUE THREAD

**Issue by robin-snt** [tpope/vim-fugitive#1294]
I'm always using this to get a graphic representation of the git tree, and now it stopped working for some reason.

Could you perhaps add this as a feature to fugitive, where you could navigate the graph and have `"Gedit` open on the commit?

**Comment by tpope** [comment]
What changed is `:Git` now only uses `:terminal` for a few select commands rather than everything. The behavior you want is on `:Git! log ...`, with the caveat `--graph` isn't supported by the syntax highlighting.

**Comment by robin-snt** [comment]
Thank you for the support. Is there any possibility of being able to configure if `:terminal` or shell? From what I understand, shell is run non-interactive for NeoVim, so ascii escape codes are ignored. Is there anything I can do or look into so that escape codes are being parsed for the `Git log --graph` command?

While searching through the issues, I read a comment where you were considering extending fugitive with a plugin interface. Has this been implemented? If such an interface would be in place, would it be possible to get colour support again, with the added ability to hit enter on a line containing a git sha and be taken to Glog/Gedit interface for that commit?

**Comment by tpope** [comment]
> Thank you for the support. Is there any possibility of being able to configure if `:terminal` or shell?

I plan to explore `:Git` subcommand special casing after 3.0, and once some defaults are in place, I may add configuration if it makes sense. (I won't be bolting on a half baked measure in the meantime.)

>  From what I understand, shell is run non-interactive for NeoVim, so ascii escape codes are ignored. Is there anything I can do or look into so that escape codes are being parsed for the `Git log --graph` command?

Nothing to do with the shell, per se. Vim gives `:!` full control of the terminal and Neovim doesn't. The offiicial solution is `:terminal`, but that's a different interaction model.

> While searching through the issues, I read a comment where you were considering extending fugitive with a plugin interface. Has this been implemented?

Not sure what you're referring to. Fugitive has had an API for third party plugins for most of its history. That API won't let you hack up the internals of `:Git` but it will let you make a `:Gmylog` command that does whatever the heck you like.

> If such an interface would be in place, would it be possible to get colour support again, with the added ability to hit enter on a line containing a git sha and be taken to Glog/Gedit interface for that commit?

`:terminal git log` uses `less` to paginate output, trying to build interactive features on top of that would make for a terrible user experience. My recommendation would be to try to add additional syntax highlighting to `:Git! log --oneline --decorate --graph --all` in `after/syntax/git.vim`. If you don't care about highlighting the lines (which seems pretty low value?) the rest of the highlighting should be pretty straightforward to implement.

**Comment by robin-snt** [comment]
> Fugitive has had an API for third party plugins for most of its history. That API won't let you hack up the internals of :Git but it will let you make a :Gmylog command that does whatever the heck you like.

Is this documented anywhere? I cannot find it in the help file (`fugitive.txt`).

> If you don't care about highlighting the lines (which seems pretty low value?) the rest of the highlighting should be pretty straightforward to implement.

I would beg to differ. Keeping the line colours would be pretty high value when you have to keep track of branches zig-zaging eachother.

Thank you so much for your support and contributions!

**Comment by tpope** [comment]
Try this for starters:

```viml
autocmd User Fugitive command! -buffer Gmylog exe 'terminal' FugitivePrepare(['log', '--oneline', '--decorate', '--graph', '--all']) <args>
```

Documentation is lacking. I've got some documentation for the public functions like `FugitivePrepare()` mostly ready. Need to come up with something for other interface points like the autocommands.

**Comment by tpope** [comment]
I've decided to make `:Git --paginate` force a terminal. This is subject to change once I figure out how subcommand special casing will work after 3.0.

The above example can be simplified to the following (now with additional argument support):

```
autocmd User Fugitive command! -buffer -nargs=? Gmylog <mods> Git --paginate log --oneline --decorate --graph --all <args>
```

**Comment by robin-snt** [comment]
Pulled the latest commits and can confirm that it works.

Amazing! Thank you so much!

**Comment by robin-snt** [comment]
Can we reopen this issue? I'm on 4606640 and the above fix no longer works.

You mentioned something about subcommand special casing, post v3. Has this been settled, and if so what's the new way to fix this problem?

Thank you.

**Comment by robin-snt** [comment]
> ```viml
> autocmd User Fugitive command! -buffer -bar Gmylog exe 'terminal' FugitivePrepare(['log', '--oneline', '--decorate', '--graph', '--all'])
> ```

Actually, this works again. But I'm still interested in understanding what has changed post v3.

**Comment by tpope** [comment]
The following relevant changes have happened since roughly the time when this issue was created.

* `:Git foo` now effectively equivalent to `:Gfoo` when the latter exists. For example, `:Git push` calls `:Gpush`, and `:Git commit` calls `:Gcommit`. This is the "subcommand special casing" I was referring to, and for now, it remains a private interface.
* A few chatty commands, notably `:Git log`, now force a temp buffer like `:Git!`, even if a bang wasn't given. This also falls under "subcommand special casing".
* Commands are now global. This means you can change `autocmd User Fugitive command! -buffer -bar` to `command! -bar`.
* I thought `--paginate` was a no-op for commands that already paginated, but it actually replaces Git's configurable pagination with a dumb call to `PAGER`. This makes it a terrible fit for a general `:terminal` flag, and a great fit for doing custom pagination of our own inside of Vim, so that's what it does now. It's the same behavior as `:Git!` and intended to ultimately replace it. I haven't decided what, if anything, should provide the old `:terminal` behavior.
* All public functions are documented as inline comments in `plugin/fugitive.vim`. Related: `:terminal` on Vim 8.1 (not Neovim) takes an argument list, not a shell command, so you'll need to do something like `exe 'terminal' &shellcmd &shellcmdflag fnameescape(FugitivePrepare(...))` for it to work there.
* (This one is brand new.) `:Git` no longer uses `:!` but rather a custom job based runner. This runner is capable of handling file edits, so commands like `:Gcommit` - which previously needed to do all sorts of shenanigans to edit the commit message - have been reduced to simple stubs that delegate to `:Git`. The general purpose nature of this change mean I no longer see much of a reason for "subcommand special casing" to become a public interface.
* (This one is coming soon.) Old wrapper commands like `:Gcommit` and `:Gpush` are now softly deprecated in favor of using the `:Git` equivalent.

I am 100% convinced at this point that the fundamental issue here is syntax highlighting. If you want to continue to work around it with `:terminal`, I won't try to stop you, but I don't really see that as a compelling justification to bake in support for it.

**Comment by robin-snt** [comment]
Thank you so much for your continued efforts, help and time.

I fully understand that you do not want to support such a small edge case.

As long as I have some means to quickly get a decorated git log in Vim, I'm a happy camper.

**Comment by tpope** [comment]
At the highest level I would not consider this an edge case. `log` is one of the most important commands in Git and do hope to improve Fugitive's interface to it. I don't think `--graph` highlighting is in the cards, though, unless we do something barbaric like force `color.ui=always` and highlight the ansi escape sequences directly.

See also https://github.com/tpope/vim-fugitive/issues/1415 for a recent change that may prove helpful.
