### ISSUE TITLE
Support :Gblame --reverse

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1305]
Git needs revision range for that, but given :Gblame is already 'bound' to the current revision of the file we can enable it for blobs only and use <current>..HEAD range

**Comment by tpope** [comment]
Adding `--reverse` to the white list if we're blaming a blob should be the entirety of the change, correct? Looks like `..HEAD` is appended by default if a commit rather than a commit range is given.

**Comment by odnoletkov** [comment]
Right, it just works as expected if I add `--reverse` to the whitelist – for the blob case. For the file case git errors with
> fatal: --contents and --reverse do not blend well
Not sure if it worth special casing and giving a more clear error

**Comment by tpope** [comment]
This option is really weird when opening the commit, as it's actually the *descendant's* patch that has the line we want, and I'm not sure a good way to find that descendant.

**Comment by odnoletkov** [comment]
Yeah, you have to manually do the next step. I open the blamed commit and run
```
:Git log --ancestry-path --reverse <commit>..
```
And the first commit would be my target.

I'm sure this can be automated but how that would look from the UI standpoint? New map 'Open descendant'?

**Comment by odnoletkov** [comment]
The "official" way is similar at least when the option was introduced: https://github.com/git/git/commit/85af7929ee125385c2771fa4eaccfa2f29dc63c9

**Comment by tpope** [comment]
I think the `<CR>` family of maps should always target the descendant, because really they're "show the patch that changed this line" maps, the fact it's different from the SHA under the cursor isn't really relevant. For the reblame maps I'm not sure, but I'm inclined to use the descendant for consistency.

The problem with the `--ancestry-path`/`--children` solution is that it can't pick the correct child in the case of a merge, but it seems like the best we can do without looking at every single descendant's patch, so I'm hooking it up.
