### ISSUE TITLE
Diff against blobs in :Gdiffsplit!

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1348]
Currently it diffs against index entries – `:2:path` and `:3:path`. This can be changed to diff against blobs – `HEAD:path` and `MERGE_HEAD:path` (need to confirm this will work for all merge cases such as rebase, cherry-pick, revert etc.).

Benefit of having blobs is it is easy to jump to commits from them with <kbd>\<CR\></kbd>. This is especially useful for resolving complex conflicts – looking at commits helps understanding both sides intentions and resolve the conflict properly.

**Comment by tpope** [comment]
Sounds handy but I don't think it's viable, as it conflicts with other behaviors like `:Gwrite` closing the other buffers, because now we can no longer distinguish between conflict buffers and arbitrary blobs.

But in case I change my mind, is this guaranteed to produce the same results, including in cases like rebases and octopus merges?

**Comment by tpope** [comment]
Also, `:.Gblame` appears to do the right thing in the index buffers - is this just an issue of whether or not `<CR>` is mapped?

**Comment by odnoletkov** [comment]
You are right – :Gblame actually does work properly from index buffers! I don't mind using `.Gblame` instead of <kbd>\<CR\></kbd> in them. So the issue is non-existent.

I had no idea git blame has special handling for the merge conflict state. The fact that it blames lines from the remote side of the conflict to commits from the MERGE_HEAD is just mind blowing to me.
