### ISSUE TITLE
Enable fugitive in diff output buffers

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1366]
For example I often `:Git diff @{U}...` to get an overview of all changes in the branch. It would be great to have same features as in commit buffers available there. Such as various maps to navigate the diff itself or jumps from lines of the diff to files and diff splits.

**Comment by tpope** [comment]
These buffers are modifiable (for that stupid `:Gwrite` to stage feature). That eliminates most maps as possibilities. A lot of them wouldn't work anyways because we don't know what commits are being diffed.

Most of the jump maps, like `]]` and `)`, could still be made available, if you want to investigate that.
