### ISSUE TITLE
Error calling :Gdiffsplit from :Gstatus buffer

### ISSUE THREAD

**Issue by mgaffney** [tpope/vim-fugitive#1367]
I updated to 973d814e26db486d6b4d46a3dfed56be612bd759 and now I'm getting the following error when I do `dd` on a changed item in the `:Gstatus` buffer:

```
Error detected while processing function <SNR>34_StageDiff:
line    4:
E716: Key not present in Dictionary: sub =~# '^S'
```

I stripped everything out of my `vimrc` file and I still get the error. Here's my `vimrc` for reference:

```vim
" Install vim-plug {
	if empty(glob('~/.vim/autoload/plug.vim'))
	  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
	      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
	endif
" }
" LoadPlugins {
	call plug#begin('~/.vim/plugged')
		Plug 'tpope/vim-fugitive'
	call plug#end()
" }
```

**Comment by mgaffney** [comment]
I reverted to the previous commit (a21ca7e86e0daf8246db791c0084086b87cdc586) and I no longer get the error.

**Comment by odnoletkov** [comment]
I broke that by removing the 'jump to submodule' feature from the recent submodules pull request shortly before it got merged 😕 One of the removed changes was still used in the PR – and I never realized because I kept using the feature locally…

Fixed in https://github.com/tpope/vim-fugitive/pull/1368
