### ISSUE TITLE
Extra line breaks with 0Glog when ussing prettify 

### ISSUE THREAD

**Issue by blasco** [tpope/vim-fugitive#1369]
I would like to customize the output of 0Glog (basically to show the date). I've tried passing the --pretify argument, and it works, but it seems a breakline is added after each message. Is there a way to solve this? 

My console output:

![Screenshot_2019-10-07_10-39-41](https://user-images.githubusercontent.com/3214400/66297041-252c5180-e8ef-11e9-9145-bf35f1dd2a2a.png)

0Glog output:

![Screenshot_2019-10-07_10-42-05](https://user-images.githubusercontent.com/3214400/66297042-252c5180-e8ef-11e9-9cd4-5f287b96d62f.png)

With the normal Glog it seems to be working fine, it only happens with 0Glog.

**Comment by blasco** [comment]
These extra lines also break completely the formatting when trying to use --graph

**Comment by tpope** [comment]
`--pretify`? `--prettify?` I don't see either of these in the `git log` manpage.

**Comment by blasco** [comment]
My fault, sorry. I mean "--pretty". This is the command that I used:

`git log --pretty=format:"%h %cd %an %s"`

**Comment by tpope** [comment]
The blank line seemingly happens from specifying `--format` a second time, but that's the least of your worries, because Fugitive has no idea how to parse a format you invented, so all those quickfix entries are just plain text that can't be jumped to. You can use something closer to the built-in formatting - `--pretty=format:"commit %H %cd %an %s"` - to get something Fugitive can recognize.

Alternatively, you can assign `g:fugitive_summary_format` if you want to control the default text description.
