### ISSUE TITLE
Windows gVim :Gwrite symlinked files

### ISSUE THREAD

**Issue by mg979** [tpope/vim-fugitive#1432]
In Windows gVim (not `win32unix`), `:Gwrite` doesn't work on files that are in symlinked directories (but `:Gstatus` works). It says that the file is _outside repository_.

In `win32unix` and `nvim` it works instead (it changes the buffer name to the real path).

For gVim (`win32`), I could fix it by changing https://github.com/tpope/vim-fugitive/blob/6bc345f6f16aee0dcc361f2f3bf80e4964f461af/autoload/fugitive.vim#L792 with
```vim
    return FugitiveVimPath(empty(url) ? a:url : has('win32') ? resolve(url) : url)
```

**Comment by tpope** [comment]
Where is the symlink, where is it pointing, and where is the repository?

**Comment by mg979** [comment]
![Imgur](https://i.imgur.com/2DkGNXk.jpg)

Real path: 

    D:\Gianmaria\Dropbox (Personale)\Linux\vimrc\plugin\buffer_history.vim

and repository in

    D:\Gianmaria\Dropbox (Personale)\Linux\vimrc\plugin

**Comment by tpope** [comment]
You said the symlink was a directory. I ask where the symlink is and you give me a file. I also asked where it's pointing and you did not answer. I can't help you if you won't answer my questions.

**Comment by mg979** [comment]
Sorry, it was late and I was sleepy. The symlinked directory is the same as the repo, I have:

```
~\vimfiles                                   (not symlinked, real path)
~\vimfiles\plugin                            (symlink to D:\Gianmaria\Dropbox (Personale)\Linux\vimrc\plugin, that is also a repo)
                                             (repo is also readable here -> ~\vimfiles\plugin\.git)
~\vimfiles\plugin\buffer_history.vim         (:Gwrite here gives problems)

:Gwrite in the real file path (D:\Gianmaria\Dropbox (Personale)\Linux\vimrc\plugin\buffer_history.vim) works.
```

I understand that fighting with Windows paths is very annoying, just saying that fugitive isn't perfect in gVim on Windows, I had other issues as well, I didn't want to bother and I can also understand if you don't consider Windows a top priority. I just had an issue and I reported it, feel free to ingore it if you don't think it's worth wasting time on it.

**Comment by tpope** [comment]
On initialization, Fugitive checks if the current file is a symlink, and if so, calls `cd .`. On UNIX, and presumably `win32unix` since it's working there for you, this forces the current buffer to have its name resolved.

https://github.com/tpope/vim-fugitive/blob/08601f221a336d13a606b33714e5a1e8457b07f7/plugin/fugitive.vim#L212-L215

If you can find a way to force the buffer name to resolve on win32, we can do that as well. I would start with `exe 'cd' fnameescape(getcwd())`.

Throwing `resolve()` elsewhere is a game of whack-a-mole, plus it adds IO to things that are supposed to be fast. It's not a tenable solution.

**Comment by mg979** [comment]
Ok I'll try to do that, thanks.

**Comment by mg979** [comment]
What I could figure out is that in Windows something work differently with git.
I did some testing and I think that the problem lies in Git for Windows, that works differently, in that it doesn't realizes that the two files belong to the same repository. The command gives an error also if run from the terminal (cmd.exe).

I updated git, just in case, but the error persists. I think only a `resolve()` call in the `:Gwrite` command for `win32` can fix this.

These are the `cmd` generated in https://github.com/tpope/vim-fugitive/blob/c83355d5c52002f94d08267f1d14ca6d1a2763e9/autoload/fugitive.vim#L429
  
```
WLS Debian (neovim), also here $HOME/.vim/plugin is a symlink to the Dropbox directory,
 :Gwrite works and the file path is changed to its resolved path

['-C', '/mnt/d/Gianmaria/Dropbox (Personale)/Linux/vimrc/plugin',
 '--literal-pathspecs', 'add', '--',
 '/home/gianmaria/.vim/plugin/buffer_history.vim']
```  

```
gVim Windows, also here the starting paths are different, but the command doesn't work

['-C', 'D:/Gianmaria/Dropbox (Personale)/Linux/vimrc/plugin',
 '--literal-pathspecs', 'add', '--',
 'C:/Users/Gianmaria/vimfiles/plugin/buffer_history.vim']
```

I also tested the same commands in the terminal (WSL and cmd.exe)

```
In WSL terminal, this works

$ git -C /mnt/d/Gianmaria/Dropbox\ \(Personale\)/Linux/vimrc/plugin --literal-pathspecs add -- /home/gianmaria/.vim/plugin/buffer_history.vim

In cmd.exe, this doesn't work:

C:\Users\Gianmaria\vimfiles\plugin>git -C "d:\Gianmaria\Dropbox (Personale)\Linux\vimrc\plugin" --literal-pathspecs add -- c:\Users\Gianmaria\vimfiles\plugin\buffer_history.vim
```

**Comment by tpope** [comment]
This is news to me, but I don't believe it changes anything. Fugitive only passes an absolute path if it can't figure out the appropriate relative path, because older Git versions didn't support absolute paths at all. The core problem remains: Fugitive expects your buffer name to not be a symlink.

**Comment by mg979** [comment]
This would fix it:
```
  let file = s:winshell() ? resolve(file) : file
```
just before

https://github.com/tpope/vim-fugitive/blob/c83355d5c52002f94d08267f1d14ca6d1a2763e9/autoload/fugitive.vim#L4605-L4610

**Comment by mg979** [comment]
Since the problem is with Git for Windows (imho), I can't think of anything else.

**Comment by tpope** [comment]
The problem is not with Git for Windows. You pointed out the real problem in your initial post (emphasis my own).

> In `win32unix` and `nvim` it works instead (**it changes the buffer name to the real path**).

All of Fugitive is built around the assumption that the buffer name is the the real path. At first I ignored this, but then bugs cropped up when people called `:cd` and the buffer name changed from a symlink path to a real path mid flight, so my solution was to force a `:cd .` early, thus preventing symlink paths from ever entering the equation. What you've told me is that this `:cd .` doesn't work. Two solutions spring to mind:

1. Find a way to make it work (where "make it work" is "resolve symlink in the buffer name").
2. If there is no way to make it work, then the original bug is irrelevant. Stop calling `resolve()` on the Git dir and work tree and everything should be back to matched up.

The following solutions do not spring to mind:

1. Change the semantics of one public function by adding `resolve()` to it, and verify that the one command that is confirmed broken is fixed.

Please stop doubling down on the bad idea that I told you is bad, and try the thing I asked you to try:

> I would start with exe 'cd' fnameescape(getcwd()).

---

Ironically, after I started writing this you edited in a decent idea.

> I made a mapping to resolve current file, and it works with it:
> 
> ```
> nnoremap \f\ :exe 'file' resolve(@%)<cr>
> ```

See also https://github.com/tpope/vim-fugitive/pull/814#issuecomment-446767081 where I attempt to provide a more robust way to do this automatically. This is the sort of thing I would consider doing, but getting to work right requires calling `edit` to reload the file, and I worry that editing the file from `BufReadPost` will cause non-obvious bugs. I would encourage you to try it, at least until the issue is fixed.

**Comment by mg979** [comment]
I think I'll use that `Resolve` command of your post and chain it with my `Gwrite` mapping
```
nnoremap \gw :Resolve<cr>:Gwrite<cr>
```
and it should be ok, thanks.

About the issue not being with Git for Windows, I doubt it, because in Linux git commands autoresolve links, in Windows they do not. Because this works in Linux
```
$ git -C /mnt/d/Gianmaria/Dropbox\ \(Personale\)/Linux/vimrc/plugin --literal-pathspecs add -- /home/gianmaria/.vim/plugin/buffer_history.vim
```
and in Windows it does not. But it doesn't matter if I can get it working in one way or another.

**Comment by tpope** [comment]
Holy fuck dude, I spent literally an hour explaining the problem in *immense* detail and gave you one simple task to help me come up with a solution, and your response it to repeat the same exact red herring I debunked. I wrote the code, I know how it works. You can't even follow simple directions, I don't know why you think you're qualified to diagnose the problem.

If anyone else has this problem, please open a new issue, I'd love to get it solved.
