### ISSUE TITLE
Autocmd for initialization in worktree files

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1441]
For example, I want to map `:Gblame` in worktree files (but not in blobs).

I used to do it in `User Fugitive` but doesn't work since https://github.com/tpope/vim-fugitive/commit/9d62c677378f5ac5abaa8229eb49aaf133fba3fa#diff-4c8459efc2f0fea43a9d26047a9e5e06L6332

**Comment by tpope** [comment]
`:Gblame` is global now; any reason your map can't be?

**Comment by tpope** [comment]
I guess your "not in blobs" qualifier raises the question "why not"? Can you have a global map that is overridden with a `FugitiveBlob` event?

**Comment by odnoletkov** [comment]
Specifically I want to map `<CR>` to `.:Gblame` in worktree files as it does in blobs. Previously I did that with:

```
autocmd User Fugitive
      \ if mapcheck('<CR>', 'I') ==# "" && getcmdwintype() ==# "" && &filetype !=# "qf"|
      \   nnoremap <silent> <buffer> <CR> :.Gblame<CR>|
      \ endif
```

**Comment by tpope** [comment]
A global `<CR>` won't override the quickfix window behavior ... but it does apparently override the command window behavior. That's weird. But you should be able to use `BufNewFile,BufReadPost` instead. You can check `!empty(FugitiveGitDir())` if you *really* need to guarantee a Git repository, but you might have to do some cleverness to get the autocommand to trigger after Fugitive's own autocommand.

I've removed this autocommand because I want to flush out all its uses to find out if lazy initialization is viable. I've already [burned myself](https://github.com/tpope/vim-heroku/blob/d654e7ac4054483f550a8216b9cf5f16b74deba6/plugin/heroku.vim#L338) as well, so I'm certainly aware of the costs imposed. There will be a cleverness free solution in place by the next release, but in the mean time, you'll have to make do.

**Comment by odnoletkov** [comment]
Inverse for me – can remove the command window guard but have to leave the quickfix. The out-of-repo case is minor, so going with

```
autocmd BufNewFile,BufReadPost *
      \ if mapcheck('<CR>', 'I') ==# "" && &filetype !=# "qf"|
      \   nnoremap <silent> <buffer> <CR> :.Gblame<CR>|
      \ endif
```

**Comment by tpope** [comment]
I'm bringing this back until I've time to plan things out a bit more. It's still almost certainly going away eventually so I'd encourage migrating away from it where possible.

**Comment by tpope** [comment]
> Inverse for me

I'm talking about a *global*, not `<buffer>` map. Command windows don't trigger `BufReadPost` so that's why you don't need the guard.

**Comment by odnoletkov** [comment]
I see, anyway *global* `<CR>` map does override *both* quickfix and command window `<CR>` for me – so can't use that

**Comment by tpope** [comment]
I've changed `FugitiveGitDir()` to lazily trigger detection if called before `FugitiveDetect()`. So the solution to this problem will be to check `!empty(FugitiveGitDir())` in `BufReadPost` or whatever other autocommand makes sense.
