### ISSUE TITLE
On staged files in`:Gstatus`, open the real file instead of the ` fugitive://.git//` one

### ISSUE THREAD

**Issue by GabrielDuarteM** [tpope/vim-fugitive#1471]
Sometimes I have staged files and, before committing them, I normally do a mini code-review on it, just to double-check. Sometimes I find stuff that shouldn't be in that commit, so I press `<CR>` to open the file, but because it is already staged, it opens the `fugitive://.git//...` file, instead of the original one. I was wondering if there's a way of always opening the original file, regardless of when it is staged or not (probably via a different `map`). 

I know that if I edit the file on `fugitive://.git//...`, it will automatically add that to the staged files, but because I edited it directly, it will diverge from the original file, and the original file will show as an unstaged change. 
I feel like a better and more natural workflow would be if I could go to the original file directly, fix the mistake, and then add the change to the staged changes, instead of fixing the staging change and then rolling back the new unstaged file (which is the original file).

What do you think?

**Comment by tpope** [comment]
It does open the work tree file if you press `<CR>` on the filename. It only jumps to the index version if you press `<CR>` on a line of the diff, because that diff is only guaranteed to be valid for the index version. If you invoke `:Gedit` from that index version, it will do the best it can to get you back to the same line in the work tree version. I don't think "best it can" is a good thing to promote to the default.
