### ISSUE TITLE
Limit maximum number of logs when using :Glog

### ISSUE THREAD

**Issue by comatory** [tpope/vim-fugitive#1475]
I'm working on a very large codebase with hundreds of branches and thousands of commits (around 40000). Sometimes I do `:Glog` without specifying the limit which in turn "freezes" nvim for up to 2 minutes before it lists all the commits.

Is there a configuration that I could set a limit to prevent this by doing accidentally (Ideally with a text info specifying that this limit is activated)?

**Comment by tpope** [comment]
It's not completely frozen, ctrl-c should interrupt it.

I would encourage you to use something like `:Git log --oneline` instead of `:Glog`, as I aim to ultimately remove the latter for among other reasons the performance problems with the quickfix list you've cited. I don't think implementing a band-aid configuration option would be a good use of anyone's time.
