### ISSUE TITLE
Show more commits on the summary page

### ISSUE THREAD

**Issue by Ram-Z** [tpope/vim-fugitive#1482]
The summary page shows a list of unpushed commits by default, I suppose it shows the list of commits not yet on `@{upstream}`. Would it be possible to configure that to show the list of commits not yet on another ref (like `master`). It would make it easier to fixup commits that have already been pushed.

**Comment by tpope** [comment]
It shows not yet on `@{upstream}` and a separate section for not yet on `@{push}` (assuming they aren't the same thing). I recommend setting your upstream to master and optionally setting `push.default` to `current`.

**Comment by Ram-Z** [comment]
Thanks for your suggestion. I had thought of something similar after opening the issue and looking into various ways of using `@{upstream}` and `@{push}`.

I would have to adapt my workflow, so far I've always had `@{upstream}` setup to track the same branch, which is quite handy to simply run `git pull` to rebase (assuming `pull.rebase=true`) onto changes that I may have pushed to that branch from another machine. To rebase on master I would run `git pull origin master`, which is a very deliberate command.

By changing `@{upstream}` the pull commands are now inverted, i.e. `git pull` will rebase onto `master` and to pull in changes from the same branch on the remote I'd have to `git pull origin <branch>` (which will be different for each branch :disappointed:  ).

Actually the more I think about this the more I reckon that I would get quite frustrated by this workflow (unless I missed something).

**Comment by tpope** [comment]
"I want to rewrite commits that have already been pushed" and "I want to blindly pull the same branch on multiple machines" are not compatible workflows. You certainly *can* do it if you're careful, but you're really going against the grain here; it's not really surprising that this bubbles up to Fugitive as well.

That's not to say I'm *opposed* to Fugitive doing more to help. But the obvious solutions, like a global option to always compare to master, are worst than the disease, in my opinion.

**Comment by thatsmydoing** [comment]
I've also tried changing my workflow to have `@{upstream}` be `origin/master` but there is a lot of friction elsewhere too,

`git status` shows your ahead/behind relative to `@{upstream}` but now we want it to be `@{push}`. Arguably, this can be correct but it's something different.

Prompt plugins typically rely on `git status --porcelain` which also only considers `@{upstream}` so those would change too. One could patch them to show it relative to `@{push}` instead / in addition to, but that's also more work.

`git switch` automatically sets up `@{upstream}` if you switch to a remote branch. This can be disabled but we now have to remember to set the upstream to `origin/master` when checking out remote branches. Local branches could take advantage of `--track=inherit` to have it automatically setup from the `master` branch.

I do understand why we don't want a simple flag for this, but I don't think changing the workflow is feasible given how git currently works.

I don't really have any concrete suggestions for how to make this work though but more customization of the summary page would be nice given how central it is to fugitive. My current workaround here is to have a binding for
`Git log --reverse --oneline origin/HEAD..HEAD` but it would be a lot nicer to have it in the summary page directly.

**Comment by tpope** [comment]
See https://magit.vc/manual/magit/The-Two-Remotes.html for a bit more context as to the rationale.

> I've also tried changing my workflow to have `@{upstream}` be `origin/master` but there is a lot of friction elsewhere too,
> 
> `git status` shows your ahead/behind relative to `@{upstream}` but now we want it to be `@{push}`. Arguably, this can be correct but it's something different.

While I might want `git status` to tell me "ahead" with respect to the push destination, I have a much stronger interest in it telling me "behind" with respect to the upstream, because that means I might want to rebase. As you say, it's arguable, but I'd be on the other side of the argument here.

> Prompt plugins typically rely on `git status --porcelain` which also only considers `@{upstream}` so those would change too. One could patch them to show it relative to `@{push}` instead / in addition to, but that's also more work.
> 
> `git switch` automatically sets up `@{upstream}` if you switch to a remote branch. This can be disabled but we now have to remember to set the upstream to `origin/master` when checking out remote branches

I don't think I understand this use case. The primary time I care about a branch's relation to `origin/master` is when I'm creating a short-lived branch that I intend to get merged/rebased into `origin/master` in the near future. There are times when I would want this for an existing remote branch (e.g., taking over someone else's work), but these are edge cases.

> Local branches could take advantage of `--track=inherit` to have it automatically setup from the `master` branch.

I've begrudgingly taken to using an alias to create branches.

```
[alias]
	work = checkout @{upstream} -t -b
```

One big advantage that Magit has is they ship their own branch management porcelain, so they aren't held back as much by the limitations of the Git CLI. But the good news is that `--track=inherit` is [actually *newer* than](https://github.com/git/git/commit/d3115660b4cc4b1a32e77ddfd289afde5e4b94d8) than Fugitive's use of `@{push}`. Git is slowly catching up to us. :)

> I do understand why we don't want a simple flag for this, but I don't think changing the workflow is feasible given how git currently works.
> 
> I don't really have any concrete suggestions for how to make this work though but more customization of the summary page would be nice given how central it is to fugitive. My current workaround here is to have a binding for `Git log --reverse --oneline origin/HEAD..HEAD` but it would be a lot nicer to have it in the summary page directly.

When I first saw `origin/HEAD` here, a light bulb appeared above my head, but then I was quickly reminded of the fact that `origin/HEAD` is only set during cloning. It can't be relied upon.

**Comment by thatsmydoing** [comment]
I did read up on the rationale for `@{upstream}` and `@{push}` and it does make sense to me. Thinking about it in terms of github PRs, `@{upstream}` would be the PR "base" and `@{push}` is your PR "head". I suppose these just aren't used much so the tooling (git cli etc.) makes it a bit awkward to work with. Reading this issue was actually the first time I've heard of `@{push}`, I knew about `@{upstream}` from somewhere on the internet but I have no idea where these are in the git documentation.

> While I might want `git status` to tell me "ahead" with respect to the push destination, I have a much stronger interest in it telling me "behind" with respect to the upstream, because that means I might want to rebase. As you say, it's arguable, but I'd be on the other side of the argument here.

It's actually more important for me to know if I'm "behind" with respect to the push destination. That could be either because the remote has changed and I need to update my local branch or I've rebased locally and now have to force push. I think it would actually be best if `git status` showed relative to both like fugitive does.

> I don't think I understand this use case. The primary time I care about a branch's relation to `origin/master` is when I'm creating a short-lived branch that I intend to get merged/rebased into `origin/master` in the near future. There are times when I would want this for an existing remote branch (e.g., taking over someone else's work), but these are edge cases.

I think my workflow is what's called "clean, linear history" so anything not on `origin/master` is free to be rewritten. So I might push a work in progress commit to a branch and squash it later. Fixups for commits I've previously pushed are quite common so being able to see all commits since `origin/master` is helpful there. In general though, it's just nice to have an overview of what I've done in the branch especially if you're switching between branches / repos a lot. It's kind of like looking at a github PR.

> When I first saw `origin/HEAD` here, a light bulb appeared above my head, but then I was quickly reminded of the fact that `origin/HEAD` is only set during cloning. It can't be relied upon.

You can do `git remote set-head origin --auto` to set it after the fact. But agreed that it's not perfect and it would be nice if it gets set by `git fetch` or similar.

I suppose it's also not always correct to use `origin/master` as a reference. In certain cases you might want to have your code merged into a different branch and `@{upstream}` and `@{push}` actually handle that case perfectly. I might take another look to see how much work it would be to switch but in the meantime I've just patched fugitive to add another section for `origin/HEAD..@{push}`

**Comment by tpope** [comment]
> Reading this issue was actually the first time I've heard of `@{push}`, I knew about `@{upstream}` from somewhere on the internet but I have no idea where these are in the git documentation.

See git-rev-parse(1). Tons of good stuff in there.

> > I don't think I understand this use case. The primary time I care about a branch's relation to `origin/master` is when I'm creating a short-lived branch that I intend to get merged/rebased into `origin/master` in the near future. There are times when I would want this for an existing remote branch (e.g., taking over someone else's work), but these are edge cases.
> 
> I think my workflow is what's called "clean, linear history" so anything not on `origin/master` is free to be rewritten.

Same.

> So I might push a work in progress commit to a branch and squash it later.

> Fixups for commits I've previously pushed are quite common so being able to see all commits since `origin/master` is helpful there.

Same.

> In general though, it's just nice to have an overview of what I've done in the branch especially if you're switching between branches / repos a lot.

Same.

> It's actually more important for me to know if I'm "behind" with respect to the push destination. That could be either because the remote has changed and I need to update my local branch...

Wait what? Why would the remote push destination change? If someone else pushing to the same branch, than rebasing already-pushed commits is a complete nonstarter. At best, it's me working from 2 different machines, but even that is fraught.

**Comment by thatsmydoing** [comment]
> Wait what? Why would the remote push destination change?

Typically, this is just me checking out someone else's branch to play with / review and they've rebased. Though it could also be me working on a separate machine.

> If someone else pushing to the same branch, than rebasing already-pushed commits is a complete nonstarter.

That's exactly why I want to see the ahead/behind relative to the remote branch (I have this in my prompt). If I'm *only* behind, then I can just fast-forward. If I'm both behind and ahead and I haven't made any commits, I can just reset hard to the remote. In the very rare case that the history changed and I do have commits I care about, then I'll know that I need to rebase very carefully.

**Comment by Ram-Z** [comment]
I've since been setting `@{upstream}` to `origin/HEAD` and `@{push}` to the 
current branch on the remote. It works really well IMO, contrary to the 
[frustration I predicted](https://github.com/tpope/vim-fugitive/issues/1482#issuecomment-593559130).

Rebasing the current branch on `master` is now simply `git pull`. The rarer case 
where I need to pull from the current branch on the remote is easily handled by 
`git rebase @{push}`. Similar to @thatsmydoing, rewriting history on feature 
branches is allowed and encouraged.

It works great with fugitive too since it now shows the pushed/unpushed to 
upstream/push commits. And `ru` and `rp` allow choosing which to rebase against.

> Local branches could take advantage of `--track=inherit` to have it 
> automatically setup from the master branch.

I didn't know about this, I had added an alias to set upstream to `origin/HEAD` 
after the fact. Will probably integrate `--track` into my workflow now.

```zsh
alias gsum='git branch --set-upstream-to=origin/HEAD'
```

> Prompt plugins typically rely on git status --porcelain which also only
> considers @{upstream} so those would change too. One could patch them to show
> it relative to @{push} instead / in addition to, but that's also more work.

I've added the following to my `zsh` prompt.

```zsh
# Format upstream
git_status+="%{$fg[blue]%}"
[[ -z "$upstream" ]] && git_status+=" Ɇ"
(( ahead  > 0 ))     && git_status+=" >$ahead"
(( behind > 0 ))     && git_status+=" <$behind"

# Format push
git_status+="%{$fg_bold[blue]%}"
push_ab=( $(git rev-list --left-right --count @...@{push} 2>/dev/null) )
if (( $? == 0 )); then
  (( push_ab[1] > 0 )) && git_status+=" ⮝$push_ab[1]"
  (( push_ab[2] > 0 )) && git_status+=" ⮟$push_ab[2]"
fi
```

It shows both the ahead/behind for `@{upstream}` and `@{push},` using slightly 
different colours and symbols.

![image](https://user-images.githubusercontent.com/1587259/218269033-65b3c71d-7151-4aee-b887-04399735a70e.png)

i,e. 6 ahead of upstream, 242 ahead of push, and 6 behind of push.
