### ISSUE TITLE
fugitive error: patch does not apply

### ISSUE THREAD

**Issue by vinceburns** [tpope/vim-fugitive#1560]
Occasionally when I'm trying to stage hunks, I get this error that the patch does not apply. 
https://stackoverflow.com/questions/4770177/git-patch-does-not-apply
I'm guessing this is the issue that I'm seeing. Is there a way to apply the chunk with the --reject and the --whitespace=fix arguments? Any other solutions would be appreciated. 
Thanks for making an awesome tool :)
-Vince

**Comment by tpope** [comment]
You're seeing the same exact error, including the `has type 100644, expected 100755` part?

**Comment by vinceburns** [comment]
Unfortunately, I can't see the error type. This is all I can see:
fugitive: error: patch failed: <path to file>:54^@error: <path to file>: patch does not apply

**Comment by tpope** [comment]
The patch is in the `lines` variable here:

https://github.com/tpope/vim-fugitive/blob/1da7c133b109cd329060174a104e325e4d6bcc82/autoload/fugitive.vim#L3529

You can try adding `call writefile(lines, "/tmp/debug.patch")` and see what happens when you try to `git apply` it. Report back with what you find.
