### ISSUE TITLE
Feature Request: Restore last commit message

### ISSUE THREAD

**Issue by bodograumann** [tpope/vim-fugitive#1608]
From time to time, `git commit` fails when called from fugitive, because of external reasons (e.g. I fail to properly sign the commit).
In that case I need to tell fugitive to call the same commit command again.
Unfortunately when I type `cc`, I will also have to retype the whole commit message again.
This can be a slight or huge pain.

So I think it would be good, if there is some way to restore the commit message of the previous failed commit call.
It seems to me, like it is already saved in `.git/COMMIT_EDITMSG`. So what about the following workflow:

- Type `cc`
- If `.git/COMMIT_EDITMSG` exists, reuse the non-commented part of it.
- `:wq`
- Call `git commit`.
    - If it succeeds, delete `.git/COMMIT_EDITMSG`
    - If it fails, keep `.git/COMMIT_EDITMSG`

**Comment by tpope** [comment]
Please tell me if I'm missing something but this sounds like it is not specific to Fugitive. That is, if you instead use `git commit` from the command line and it fails because of external reasons, you'll have the exact same problem, correct?

If that's the case, this is not something that will be changing. Fugitive builds on Git; it does not arbitrarily "fix" upstream design decisions.

**Comment by bodograumann** [comment]
Oh, you are of course completely right. I use fugitive so freqently I didn’t realize that it happens with plain git as well.

I guess I'll try and add a mapping for `git commit -m "$(cat "$(git rev-parse --git-dir)/COMMIT_EDITMSG)")"` or something along those lines. (See https://unix.stackexchange.com/a/590225)

Adding one to the commit maps in fugitive could be in scope. It might not be used by many people though.

**Comment by tpope** [comment]
You can make that a lot less ludicrous with `git commit -F`.
