### ISSUE TITLE
spurious file created after :G1a

### ISSUE THREAD

**Issue by pavoljuhas** [tpope/vim-fugitive#1612]
After opening some file in a git worktree `:G1a` writes it as `1a` to the repository root and adds it to git index.
The expected behavior is to get *E492 - Not an editor command*.

This seems to be happening for undefined commands that match `G[0-9].*`

**Comment by tpope** [comment]
Vim commands can't contain numbers. If you call `:e1a`, that gets parsed as `:e 1a`, and edits a file named `1a`. The same thing is happening with `:G1a`, although it's getting changed to `:Gw 1a` rather than `:G 1a` which is a bit surprising. My guess would be that it's picking the shortest command that accepts `*` arguments. Nothing we can do about it at any rate.

**Comment by pavoljuhas** [comment]
I see, this trips on `help user-cmd-ambiguous`.
Even with those rules it should translate to `G 1a` because G can take an argument.
I will resubmit this as a vim bug.

**Comment by tpope** [comment]
Note that `:G` is defined with `-bar -nargs=?` while `:Gw` is defined with `-nargs=*`, I bet one of those two options is relevant.
