### ISSUE TITLE
Fugitive status show commits unique to current branch?

### ISSUE THREAD

**Issue by kvalv** [tpope/vim-fugitive#1619]
Hi,

Is there an easy way for me to list commits unique to a branch in the `:Gstatus / Git` status? For example, let's say I have
```
A - B -  E - F   <master>
       \- C - D  <mybranch, HEAD>
```
... then I would want to be able to see only commits `C` and `D` (since they only exist in `mybranch`). 

I have seen #1172 where it is mentioned that `:Git branch -u origin` is an effective solution, but this wouldn't work if `mybranch` is not pushed to remote. I _could_ set it to track `origin/master` (then it would show the commits local to `mybranch`), but I would have to set the remote to `origin/mybranch` before I push (otherwise I push directly to master). And once I've pushed the local branch, I still won't be able to see the commits that already has been pushed to `origin/mybranch`, only the new local commits. 

So is there any way for me to "customize" which commits is displayed when I open up the fugitive git status line?  Ideally I want to be able to send the contents of e.g. `git log --oneline master..HEAD` to the fugitive git status line.

Many thanks for any help I receive!

**Comment by tpope** [comment]
My recommended practice is `:Git branch -u origin/master` (I assume I was using "origin" generically in that comment, as otherwise it makes no sense), and use a `push.default` that's either `current` or the default of `simple`. This will get you two unpushed sections, one for `origin/master` and one for the identically named branch at `origin` that you'll be pushing to.
