### ISSUE TITLE
Gstatrus resizes windows

### ISSUE THREAD

**Issue by aik** [tpope/vim-fugitive#1631]
Executing "Gstatus" opens a fugitive window (good), resizes "Quickfix List" (the one opened with "copen") but after closing the fugitive window, "Quickfix List" remains 1 line long. How to disable "Quickfix List" height change or set the minimum height?

**Comment by tpope** [comment]
`:Gstatus` is a thin wrapper around `:topleft split .git/index` (or `:botright split .git/index` if `'splitbelow'` is set. Do those commands exhibit the same problem?

**Comment by sflip** [comment]
> `:Gstatus` is a thin wrapper around `:topleft split .git/index` (or `:botright split .git/index` if `'splitbelow'` is set). Do those commands exhibit the same problem?

For me they do, yes.

I sometimes have a terminal buffer in a split window at the bottom with a height of less than 50%, and after a `:Gstatus` (or `:botright split .git/index` respectively) and close of the fugitive window, the terminal window takes 50% height. I'd rather expect it to restore the original height.

@tpope can you confirm that the resizing is caused by the plugin? If so, is there a way to prevent or customize it?

**Comment by tpope** [comment]
The resizing is _not_ caused by the plugin. `:botright split .git/index` should not behave any differently than `:botright split README.md`.

**Comment by sflip** [comment]
Okay, thank you for the fast response!
