### ISSUE TITLE
Unable to discard all untracked with X

### ISSUE THREAD

**Issue by TamaMcGlinn** [tpope/vim-fugitive#1674]
In the fugitive status window, it is possible to use `s`, `u` and `X` on individual files, but also on the header 'Staged' 'Unstaged' etc. to do that operation on all the files. However, it doesn't work for the `X` command on the Untracked header.

**Comment by tpope** [comment]
In order to prevent having a one character "shoot myself in the foot" mapping, Fugitive backs up each file targeted by `X` and uses `:echomsg` to display a restoration command. This gets clumsy as the number of files increases, and I think you'd generally be better off typing out a few extra characters such as `:Git clean -f` than dealing with the overhead and mess of a full section discard. But if you want to implement it, knock yourself out; I'll entertain a PR as long as it maintains the restoration command feature. Note that recursing into untracked directories isn't currently supported either.
