### ISSUE TITLE
Opening a diff from "G diff ..." shows the same files

### ISSUE THREAD

**Issue by Gelio** [tpope/vim-fugitive#1695]
Hey, first of all, thanks for the awesome plugin!

I have been trying to figure out a workflow for reviewing PRs interactively using vim. I figured I can do

```sh
:G diff HEAD~2..
```

which opens a nice diff view, as expected.

```diff
diff --git a/configs/coc-settings.json b/configs/coc-settings.json
index 87bfc71..7a66081 100644
--- a/configs/coc-settings.json
+++ b/configs/coc-settings.json
@@ -8,6 +8,8 @@
     "javascript",
     "typescriptreact",
     "javascriptreact",
-    "json"
+    "json",
+    "go",
+    "rust"
   ]
 }
diff --git a/configs/neovim.vim b/configs/neovim.vim
index 533fc26..784f085 100644
--- a/configs/neovim.vim
+++ b/configs/neovim.vim
@@ -9,6 +9,9 @@ set smartcase
 " Scrolling offset
 set scrolloff=5
 
+" Splits
+set splitbelow
+
 " Tab width and expanding tabs
 set shiftwidth=2
 set tabstop=2
```

The problem appears when I try to `o` into some diff. When I'm on the first line and press `o`, 2 new windows open below, both of them have the same content (initially folded).

![image](https://user-images.githubusercontent.com/889383/111037125-0b1b6a80-8423-11eb-9385-ed0b6a8db1a3.png)

Buffers:
![image](https://user-images.githubusercontent.com/889383/111037161-3dc56300-8423-11eb-90f2-7b3a73801431.png)

with `dbebb...` being the current HEAD.

This leads me to think that the diff contains the same file (`/0` and `/dbebb...`), whereas I expected one of them should be the one from the previous commit, so I can actually see the diff

---

I am a vim beginner, so there's a high chance I am doing something incorrectly. I have been trying to find a way to comfortably review diffs from a range of commits, and the only thing that worked for me was `:G difftool -y`, but that opens multiple tabs and I wanted to see if there are other solutions

If there's a workflow I am missing that would let me easily review changes from a range commits (e.g. using a quickfix list) **and** do split diffs, let me know 🙂 I tried using `:G difftool` but I found that cumbersome (after going to the next quickfix entry, press `o`, then go to commit hash, and press `o` again for a split diff).

**Comment by tpope** [comment]
You're not really missing anything. The problem is that there's nothing in that `:Git diff` buffer that actually says what commits are being diffed, so Fugitive is making an educated guess and failing. A fix would be to record the arguments passed into `:Git diff` and then parse out what commits were passed in. This might happen one day: I want to add smarter jump behaviors to other buffers like `:Git branch`, and once the abstractions are in place for that, special casing `:Git diff` gets a lot more tenable. But I wouldn't cross my fingers on that landing any time soon.

In the meantime, I do recommend using `:Git difftool`. #132 has some discussion and aftermarket solutions for making it less onerous.

**Comment by Gelio** [comment]
I see, thanks for a detailed answer and pointing in the right direction
