### ISSUE TITLE
Discard section in status

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1705]
I can use stage and unstage maps on the section header to act on all files in the section. But not the discard map `X` – it does nothing on the section header.

Is it to prevent accidental data loss? Seems there are safeguards in place already: `X` needs shift, 'undo' is available. `X` also works already for multiple files with visual selection.

My use case: I have to `X` multiple submodules all the time in my project with active submodules.

**Comment by tpope** [comment]
The "undo" is clunky and scales poorly to multiple files. And I've already been over how I think section headers are an awkward interface. But if you wanna implement it knock yourself out I guess. I will never understand these requests to make the "shoot myself in the foot" gun bigger and bigger.

> My use case: I have to `X` multiple submodules all the time in my project with active submodules.

I hate to ask but why? The real thing I don't understand is people who discard changes so frequently that typing out `:Git clean` or `:Git checkout .` is a bottleneck.

**Comment by tpope** [comment]
I was confused why a regular `git checkout` would be part of any submodule workflow until I went back and looked at your submodule changes. How is `git submodule update` in any way a good fit for `X`? No wonder you want a bigger gun when you've repurposed the gun as a back scratcher.

Your undo is broken too; it abused a lack of argument handling that has since been rectified. I see no reason not to revert a21ca7e86e0daf8246db791c0084086b87cdc586 in its entirety.

**Comment by odnoletkov** [comment]
> How is git submodule update in any way a good fit for X?

`X` 'discards the change' for normal paths. In the same way it 'discards the change' for submodules. `git submodule update` to submodules is same as `git checkout` to normal paths. I don't see an issue here, can you explain?

> Your undo is broken too

Oops. Not sure this undo is really useful – since the action is non-destructive and can be reverted manually. So I'd remove it. But if you think its worth to keep it I'm happy to fix. What is the good way to `git -C $path` nowadays?

**Comment by tpope** [comment]
> > How is git submodule update in any way a good fit for X?
> 
> `X` 'discards the change' for normal paths. In the same way it 'discards the change' for submodules. `git submodule update` to submodules is same as `git checkout` to normal paths. I don't see an issue here, can you explain?

Is this any different than saying `git pull` "discards the change" between your local branch and the remote one? Feels like a stretch. Where did the changes you're discarding come from? They're upstream changes that have been integrated, correct?

**Comment by odnoletkov** [comment]
> Is this any different than saying git pull "discards the change" between your local branch and the remote one? Feels like a stretch.

Totally different. Pull brings in some new changes from the outside. `git submodule update` updates submodule state to match what is recorded in the HEAD. The former uses network, the later never does in practice. For some reason Git is smart enough to automatically *fetch* all required submodules changes when it *fetches* the superproject, but it doesn't *update* submodules checkouts automatically. So every time your `git pull` brings in some submodule changes, you get dirty status and you need to `git submodule update` manually, like an animal. In a project with frequent submodule changes this happens all the time – I got a lot of mileage from that `X` map.

Imagine merge or rebase only worked on commits and didn't touch the working tree. You would need to `git checkout` all the handing file changes manually. That's why I'm saying `git submodule update` is the same as `git checkout` for normal paths. In the status buffer my mental model for `X` is 'remove this *change*, reset this path back to HEAD version' – matches exactly what `git submodule update` does.

(all of the above is with the default configuration, `submodule.recurse` is supposed to help by automatically updating submodules checkouts most of the time – but it is new, buggy and breaks other stuff so I rarely seen it used in practice, people just `git submodule update` manually all the time)

Does it make sense? Can we return `X` back (with or without undo)?

**Comment by tpope** [comment]
1. Say I have a project with a submodule. The upstream repository has new commits I want to try out. What command do I run to do that?
2. After I run this command, I encounter a dealbreaker bug, and decide never mind, we should not update until upstream gets its shit together. What is the command I use to throw away the update I just did and go back to a pristine state?
3. I realize the bug I encountered was actually user error, and I want to go back to the version of the submodule I was just on. There are additional changes at the upstream now, and I don't want those because that would mean I would have to start testing all over again. I just want the same state I was at the first time I updated. How do I do that?

Number 2 should be the `X` operation, and number 3 should be the undo. If `git submodule update` really is correct for number 2, fine, but the fact that it's _really_ useful for business-as-usual with submodules, and that we're incentivizing the user to develop muscle memory for the "dangerous" operation, is a downside I'm merely willing to tolerate.

And if all that is indeed correct, then it does sound like `checkout -` is the right general idea for an undo. But I think it would be better if we actually captured the commit hash. I'm more concerned with having a record of what was thrown away (even if the stakes are relatively low here) than I am with having a one liner the user can run, so the lack of `-C` support isn't a big deal.

Finally, what's the deal with the `info.status ==# 'A'` case? We don't silently no-op files, we act on them or error, and the fact this `continue` slipped in is what ultimately convinced me to revert and start over.

**Comment by tpope** [comment]
And `reset` is definitely wrong. We have `u` for `reset`.

**Comment by odnoletkov** [comment]
> 1. Say I have a project with a submodule. The upstream repository has new commits I want to try out. What command do I run to do that?
> 2. After I run this command, I encounter a dealbreaker bug, and decide never mind, we should not update until upstream gets its shit together. What is the command I use to throw away the update I just did and go back to a pristine state?
> 3. I realize the bug I encountered was actually user error, and I want to go back to the version of the submodule I was just on. There are additional changes at the upstream now, and I don't want those because that would mean I would have to start testing all over again. I just want the same state I was at the first time I updated. How do I do that?
>
> Number 2 should be the `X` operation, and number 3 should be the undo.

1. `git submodule update --remote $path`
2. `git submodule update $path`
3. For this specific scenario `git submodule update --remote --no-fetch $path` would work. But it wouldn't work in other scenarios, for example when you are updating submodule yourself too. So yeah `git -C $path checkout $old_hash` is the most reliable undo

> If `git submodule update` really is correct for number 2, fine, but the fact that it's _really_ useful for business-as-usual with submodules, and that we're incentivizing the user to develop muscle memory for the "dangerous" operation, is a downside I'm merely willing to tolerate.

I see your point. Also in some projects it may be unclear whether specific path is a submodule or plain file. `git status --short` has the same issue, but not the normal `git status`:

```
Changes not staged for commit:
        modified:   some/file
	modified:   submodules/foo (new commits)
        modified:   submodules/bar (modified content, untracked content)
```

What do you think about adding these indicators in Fugitive?

Another option is using a different map for submodules, not `X`. This will also open door for more submodule-specific commands (but tbh I can't think of anything really useful). But this will not play well with group operations – visual select and section headers.

> And if all that is indeed correct, then it does sound like `checkout -` is the right general idea for an undo. But I think it would be better if we actually captured the commit hash. I'm more concerned with having a record of what was thrown away (even if the stakes are relatively low here) than I am with having a one liner the user can run, so the lack of `-C` support isn't a big deal.

Yeah using explicit hash is much better than `-`. On the general topic of undo – I think there are two types of submodules users:

* People who have to work in a project with submodules, but never update submodules themselves. So they only need to keep up with submodule updates from others, mainly resolve this issue with dirty index after pull I described. They would never want to undo the `X` because they always want submodule to match what superproject says.

* Anyone who actually works with submodules – directly modify content or just integrate submodule's upstream changes. To do that you have to actually understand how submodules work. I think these folks will `:e submodule/foo` and do what is needed there directly rather than look for the undo command in `:messages`.

I've been in both groups and never used this undo in practice. But this is obviously subjective, would be great to hear from other folks using submodules.

> Finally, what's the deal with the `info.status ==# 'A'` case? We don't silently no-op files, we act on them or error, and the fact this `continue` slipped in is what ultimately convinced me to revert and start over.

'A' means new submodule. I described these in the commit message:

```
Staged/A:
Noop. 'git rm -f' would be appropriate but it is destructive for possible
non-staged changes inside submodule and hard to undo

Unstaged/A:
Noop. Hard to reproduce in practice, 'git status' doesn't handle it well
and hard to undo
```

You are right that these should have been errors, not silent noops.

> And reset is definitely wrong.

Couldn't find a way to undo _staged_ submodule change in one command, had to do two steps

---

Btw I also made a sort of a test suite with all possible status states back then: https://github.com/odnoletkov/git-status-test-suite. You can repro all submodule statuses with `make submodules`. I'm also happy to submit a PR once we land on decisions.

**Comment by tpope** [comment]
For undo, let's use the commit SHA then. You can probably get it with something like `fugitive#RevParse('HEAD', FugitiveExtractGitDir(info.paths[0]))`. We don't need `-C` because the undo boilerplate starts with `:Gsplit` to the submodule path. And like you said, almost nobody will run this command; I just want the hash captured somewhere for reference.

For `A`, use the same template as "will not delete directory", but with "will not delete submodule". Both this and the previous change probably belong in that topmost conditional with the rest of the undo logic.

With these changes to the original logic, I will re-evaluate a fresh pull request.

> What do you think about adding these indicators in Fugitive?

I don't want to mess with the current format right now, but we could probably get away with adding a trailing slash so you can at least tell they're submodules.

**Comment by tpope** [comment]
> Another option is using a different map for submodules, not X.

I do think that is the correct solution. `X` is the stopgap until I get around to assessing and addressing the long tail of miscellaneous commands.

**Comment by odnoletkov** [comment]
Thanks for restoring this @tpope!

I've tested the new version and everything works except one thing – undo for deleted submodule paths (with status `D`). (Can repro with `make reset D_S___ _DS___` in the [test repo](https://github.com/odnoletkov/git-status-test-suite)).

    :Gsplit _DS___|GRemove
    fugitive: fatal: not removing './' recursively without -r

This undo case doesn't work because `:GRemove` doesn't work from submodule folder – makes sense since `:GRemove` is relative to the Git repo. Unfortunately even `:Git rm $submodule` from the superproject wouldn't work as a proper undo – because `git-rm` has special behavior to also change `.gitmodules` for submodules. I think the only way to undo `X` for deleted submodules is `:!rm -r $submodule` which doesn't look great.

This is really an edge case – I mean undoing a submodule 'undeletion', who does that. So I'd leave it as is. We can also disable `X` for deleted submodules.

**Comment by tpope** [comment]
Good to know.
