### ISSUE TITLE
Feature request: command to open vimdiff-style layout for the current file

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1706]
`:Gdiffsplit!` is nice but for really complex conflicts I need to see the base version. The idea is to show same layout as good old `git mergetool --tool vimidff` which many people are used to. Currently I use:

    command GMergetool only | Gvdiffsplit! | Gvdiffsplit! :1 | wincmd J

I'm sure this is full of issues and should be implemented properly, but what do you think about the idea?

**Comment by tpope** [comment]
I guess it's been a while since I've used `git mergetool` because last I checked [it did a 3 panel diff, not 4 panel](https://github.com/git/git/commit/829ef383a2b03a614d7d23e575270f2b10a805c1). It might make sense to stick the 4 panel behavior on `:Gdiffsplit` but not `:Gvdiffsplit`, or vice versa, I don't know, maybe that's too clever. I'm reluctant to ditch 3 panel entirely because I prefer it (though perhaps only because it's what I'm used to), and I don't think a configuration option is a good idea, though it's a closer call than most proposed configuration options.

**Comment by tpope** [comment]
I guess a prerequisite to this is how do we fix "full of issues"? I don't think `:Gdiffsplit` should close other windows, which renders `wincmd J` worthless, but maybe something like `:aboveleft Ghdiffsplit :1 | Gvdiffsplit! | wincmd j` would get us most of the way there?

Or maybe the fact we won't close other windows means we shouldn't be doing a 3 over 1 nightmare split, since you really need the whole tab for this feature to be usable. Or we could limit it to use case like https://github.com/tpope/vim-fugitive/issues/318#issuecomment-522221941.

**Comment by odnoletkov** [comment]
> It might make sense to stick the 4 panel behavior on :Gdiffsplit but not :Gvdiffsplit, or vice versa, I don't know, maybe that's too clever

* `:Gvdiffsplit!` is explicit, I wouldn't expect it to do any smarts like that
* `:Gdiffsplit!` is better candidate but I think this would be a pretty disrupting change?

Feels like `:G*diffsplit` already have too many behaviors to keep in mind: split direction, bang, conflict or not. Adding another dimension may be too much for the mental model.

> I'm reluctant to ditch 3 panel entirely because I prefer it

Yep, I use it too and only switch to 4 panel for complex conflicts

> I don't think :Gdiffsplit should close other windows

Agree `:Gdiffsplit` shouldn't. Can separate command close windows? Or you are reluctant to add new command for that?

> maybe something like :aboveleft Ghdiffsplit :1 | Gvdiffsplit! | wincmd j would get us most of the way there?

This doesn't work because `:Gvd!` doesn't work properly from the `:1` buffer. This abomination works though:

    :abo Ghd :1 | abo Gvd! :2 | Gvd! :3 | wincmd j

> Or maybe the fact we won't close other windows means we shouldn't be doing a 3 over 1 nightmare split, since you really need the whole tab for this feature to be usable

I think keeping other windows for this is too much. When you have other windows there is no good way – such as `:only` – to close these :1, :2 and :3 windows after you are done with conflicts – you need like 20 keystrokes.

But I'm nowhere a heavy windows user myself, so can't tell. I only see this closing the quickfix a little annoying.

> Or we could limit it to use case like #318 (comment).

You mean it will only be available from the status buffer with some map? This won't work with `:Git mergetool` which I use all the time so I guess I'd stick with custom command in that case.

**Comment by tpope** [comment]
I think `:aboveleft Ghdiffsplit :1 | Gvdiffsplit! | wincmd j` and `fugitive#DiffClose()` are as close as we're going to get in the foreseeable future. I'd be open to pursuing `:Git mergetool -y` but I'm guessing the new tab behavior greatly reduces the appeal.
