### ISSUE TITLE
`O` from status window invites accidental user overwrite of HEAD (was: fugitive ate my HEAD)

### ISSUE THREAD

**Issue by donburks** [tpope/vim-fugitive#172]
Installed pathogen and fugitive into my vim environment. 
Edited a file.
Went to :Gcommit it. Commit failed, error is:
error: unable to resolve reference HEAD: No such file or directory
fatal: cannot lock HEAD ref

And now all files in my project are listed as 'new' files that are untracked.

Now, I can fix the problem by deleting everything and doing a new checkout, but I shouldn't have to do that due to my editor plugin.

**Comment by ManasN** [comment]
vim-fugitive ate my head too. 
And I love vim-fugitive.

**Comment by nicolaiarocci** [comment]
Just had this happening to me. Scary stuff. 

I hit `:Gcommit` without a `:Gwrite` first so it went into `:Gstatus` instead, as mentioned by @tpope. I went like oh well, hit a `-` on the needed changes and then went back to top of the buffer and hit `O` to add a new line -> Bam. Fixed thanks to @mwcz note.

**Comment by tpope** [comment]
Okay, so let's ignore the fact that `O` is not how you normally start editing a commit message, nor do you ever do it in the same buffer you issue `-` in. Brain farts happen, and I get that having it take you to `.git/HEAD` is less than ideal. But then what? What is going through your head when find yourself in a completely different file, which is in a completely different tab, lacking the usual status comment, containing nothing but an unexpected SHA, and on top of all that you're not even in insert mode like you should be expecting? How do you get from there to "well I should delete this line I don't understand, go into insert mode a second time, write my commit message, and save the file"?

I don't want to trivialize this because it has obviously tripped up several people (and that's just the ones who have spoken up). But for a problem this far out into "user error" territory, I'm only willing to entertain a solution that has zero downside to regular operation. So no taking away `O` on the first line (even though it has limited value), or making `HEAD` read only (it's really not our place to do that).

**Comment by glittershark** [comment]
Add a blank line at the beginning of .git/index?

**Comment by tpope** [comment]
"Looking ridiculous" is pretty high on my list of downsides.

**Comment by nicolaiarocci** [comment]
I agree that this falls in the user error department, and finding a solution was easy. Not sure on a possible solution. Maybe simply add a note in the help file/readme/faq?

**Comment by mwcz** [comment]
I know changing the behavior of `O` is off the table, but I just want to say that because @tpope's plugins are so excellent at intuitively overriding default vim commands, this really threw me for a loop because of its weirdness.  In this case, fugitive presents the user with what appears to be a totally standard text buffer (the *exact* same thing you see if you run `git commit`), a buffer for which the first sensible action is `O`, but has a very unintuitive response to `O`.

**Comment by dragon788** [comment]
So this is why I kept hosting up my repo!?!?! I've been holding of on using the lovely vim-fugitive due to this. So workflow is Gwrite to trigger an add then Gcommit?

**Comment by tpope** [comment]
It is EXACTLY THE SAME as using it from the command line. The only thing tripping people up is that failure and success look similar because the status output is syntax highlighted.

**Comment by mwcz** [comment]
@tpope I just stepped through the process again and you're completely right.  This scenario happened to me over a year ago and my memory wasn't as clear as I thought, very sorry about that!  It's absolutely the syntax highlighting that threw me.

#### `:Gcommit`

![screenshot from 2016-01-04 10-34-16](https://cloud.githubusercontent.com/assets/364615/12093079/d0393878-b2ce-11e5-8ebf-ed858e799f4f.png)

#### `git commit` (with staged changes or -a)

![screenshot from 2016-01-04 10-34-31](https://cloud.githubusercontent.com/assets/364615/12093085/da8d7924-b2ce-11e5-89f2-950ada3e07b1.png)

They looked similar enough that I thought I was editing a commit message when I was actually looking at status. `:syn off`

**Comment by sehe** [comment]
Yep. This happens _all the time_ for me. My fingers are ahead of me and want to start typing the commit message, so **obviously** they hit `O`. 

It's never been a problem to recover - because I can just close and reopen the Gstatus, and remember to **do `cc` first**.

In all fairness:

 - the ref buffer could be readonly?
 - `O` might not be _your_ usual way to start editing a commit message, but others may never do otherwise
 - `cc` /is/ a strange combo (normally used to change a full line...)

**Comment by tpope** [comment]
I don't understand "do `cc` first". The fact you're in this predicament to begin with means you have nothing staged, which means `cc` will be a no-op.

**Comment by sehe** [comment]
Not at all. When I do Gstatus and have added stuff, I **need** to do `cc` in order to initiate a commit. Sometimes I forget (because the buffer very similar to a commit buffer) and I press `O` to start editing the commit buffer.

Nothing fancy. Literally happens at least 1 time a day. For about 2 years. And I still love fugitive.

I never thought much of it, but reading this thread, I thought I'd mention it.

I've never been in a predicament and I'm not complaining. I'm merely explaining what can happen, as I thought you have spent several messages explaining you didn't understand. If you did, ignore me!

**Comment by sehe** [comment]
Aaaand just somehow I did royally screw up finally. I don't know exactly what I did this time around that overwrote the ref file. Thanks @mwcz for your steps to safely get a recent HEAD reference.

It saved me a lot of stress fixing this.
