### ISSUE TITLE
MINGW64 - printing [80X [80C when attempting to commit

### ISSUE THREAD

**Issue by stepan-ruzicka** [tpope/vim-fugitive#1726]
Vim8.2 and MINGW64 is a part of Git SCM for Windows by default and adding vim-fugitive to it easy.

However, after attempting to commit I get the following sequence of signs. What could be wrong?

![image](https://user-images.githubusercontent.com/19532699/114211715-4432f600-9961-11eb-89d0-754c048f3058.png)

**Comment by tpope** [comment]
Is it just `:Git commit`, or are other commands like `:Git status` affected?

Does `:echo $GIT_EDITOR` show anything?

Does `:echo g:fugitive_pty` show anything? It should give an `undefined variable` error, unless you've set it.

**Comment by tpope** [comment]
Oh, please also check `:echo has('unix')` and `:echo has('win32')`. I'm not sure what the MINGW64 build of Vim reports for either of those.

**Comment by stepan-ruzicka** [comment]
`:Git status` is also affected, although it shows `^[[K` like sequences.
`:echo $GIT_EDITOR` shows nothing. 
`:echo g:fugitive_pty` gives `undefined variable` error.
`:echo has('unix')` shows 1.
`:echo has('win32')` shows 0.

**Comment by stepan-ruzicka** [comment]
Anyway, I found a solution (at least for me). Don't select "Enable experimental support for pseudo consoles" during the installation of Git for Windows.

![experimental(1)](https://user-images.githubusercontent.com/19532699/114282286-3d7caf80-9a43-11eb-94d1-40492259b4c0.PNG)

I guess this issue is not caused by vim-fugitive and can be closed?

**Comment by stepan-ruzicka** [comment]
Cross-referencing: https://groups.google.com/g/git-for-windows/c/7jP46cFOkKE

**Comment by tpope** [comment]
Fugitive uses a pseudo console (PTY) for `:Git` when possible, because a PTY enables little niceties like a progress bar on `git fetch`. Where it's _not_ possible is Windows, where a PTY brings with a bunch of garbage escape sequences that I don't know what to do with. What you've discovered is that the "experimental pseudo console" support brings those escape sequences to MINGW's otherwise very UNIX-like runtime environment.

I don't know of a way to check for this particular set of preconditions, so for now I will throw the baby out with the bathwater and disable the PTY on all UNIX for win32 environments. I'd rather a few people lose some progress bars than a few people get a broken `:Git`.

**Comment by stepan-ruzicka** [comment]
Thanks!  Just tested: vim-fugitive now works even with "experimental support for pseudo codes" enabled.
