### ISSUE TITLE
:Git blame → view patch vertically sidy-by-side

### ISSUE THREAD

**Issue by weeman1337** [tpope/vim-fugitive#1775]
I have read the fugitive and vim docs and didn't find any solution for it. Here are the experts :)  
Maybe this is more a question than a feature request:

My use case:
- `:Git blame`
- Select any commit
- Preview or enter opens the patch as inline diff

Is it possible to switch that to side-by-side view?

I have already tried setting `diffopt+=vertical`. That didn't change anything.

**Comment by tpope** [comment]
`:Gvsplit <cfile>` does what you literally describe. Personally I find the 3 vertical panes to be awkward in practice and not really worthy of a dedicated map.

**Comment by weeman1337** [comment]
Thanks for the reponse. `Gvsplit hash` shows the diff inline:

![image](https://user-images.githubusercontent.com/6216686/123505849-95e64500-d661-11eb-9d5a-81c66ea65001.png)

I am more looking for what `git diff --difftool=vimdiff hash path/to/file` does

![image](https://user-images.githubusercontent.com/6216686/123505955-fecdbd00-d661-11eb-9530-162ce77d7f62.png)

**Comment by gegoune** [comment]
Apologies for asking that here, but your colorscheme is really neat, what is it?

**Comment by weeman1337** [comment]
> Apologies for asking that here, but your colorscheme is really neat, what is it?

It is this "one" :D https://github.com/rakr/vim-one

**Comment by tpope** [comment]
I did mistakenly single out "vertical" as meaning "opposed to the horizontal default" as opposed to this being an orthogonal request. The desired behavior is actually [pretty close to `-`](https://github.com/tpope/vim-fugitive/blob/64bc1a343156512cf5896b33ff46c99fcaa36edb/autoload/fugitive.vim#L6974-L6997), only instead of blaming again, we would want to call `:Gdiffsplit!`. Although it gets trickier if we want to support `--reverse`: Then we would need to use [this trick](https://github.com/tpope/vim-fugitive/blob/64bc1a343156512cf5896b33ff46c99fcaa36edb/autoload/fugitive.vim#L6650) to find the descendant to diff against.

I have no principled objection to providing the `dd`/`ds`/`dv` family of maps in the blame buffer with the requested behavior. Stitching together the above two code fragments with a `:Gdiffsplit!` should not in principle be a huge undertaking, but the devil may lie in the details.

Note that `<CR><CR>dd` will take you first to the patch, then the blob as it stands, then finally to the desired diff. This won't work some edge cases, including but not limited to `--reverse`, but is probably good enough for most purposes.
