### ISSUE TITLE
Open in preview map doesn't work from the grep buffer

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1825]
1. `:Git grep query`
2. `fugitive_p`

throws

> E486: Pattern not found: ...

**Comment by tpope** [comment]
This is effectively happening because `:edit +/complex.pattern file` was a pain in the ass (impossible?) to escape, so I changed it to `:edit file|/complex.pattern` which of course targets the wrong window with the `:pedit` variant. One fix is to figure out the escaping. The other is to special case [the constructed command](https://github.com/tpope/vim-fugitive/blob/2a53d7924877b38b3d82fba188fd9053bfbc646e/autoload/fugitive.vim#L7728-L7730) for `pedit` to switch to the preview window and back. The latter is probably a better solution because I believe there's another obscure case or two that would get fixed in the process.

Easy workaround is `:Git grep -n query`, or enable `grep.lineNumber`. There's an argument for always forcing that on `:Git grep`, but I decided to favor matching vanilla Git's output as close as possible.
