### ISSUE TITLE
Jumping to work tree versoin with 1<CR> doesn't work

### ISSUE THREAD

**Issue by borisbrodski** [tpope/vim-fugitive#1827]
While checking the history with :Gclog I can switch back and forth between diff view and file view by pressing enter `<CR>`, that is really cool.

Now I would like to edit the file, so I need to jump to the work tree version of the file. This should be done by pressing `1<CR>`:

```
<CR>                    Open the file or |fugitive-object| under the cursor.
                        In a blob, this and similar maps jump to the patch
                        from the diff where this was added, or where it was
                        removed if a count was given.  If the line is still in
                        the work tree version, passing a count takes you to
                        it.
```

But `1<CR>` do nothing. I tried it in the diff view and in the file view (after pressing <CR> in the diff view)

The line is present in the work tree version of the file. I can open it manually.

**Comment by tpope** [comment]
"In a blob" means the file version. Try `:0,1Git blame --reverse`. What does that do?

**Comment by borisbrodski** [comment]
Thank you for the quick response.

* In the diff  `:0,1Git blame --reverse` produces the error `fatal: no such path  in 7366d3adf8...`
* In the file ('fugitive-object') it opens the work tree version of the file, puts cursor at the correct line (yahoo!), but then increases the indentation of that line (like `>>` would do)

Also, `:0,1Git blame --reverse` seams bit weird to me.  `0,1` is not the line I was interested in. Also I would `Git blame` expect to dig into history but it indeed manages to find the correct line in the work tree version of the file.

PS
You wrote absolutely insanely cool vim integration! Thank you very much :+1:

**Comment by tpope** [comment]
What does `:verbose nmap <CR>` report in the file buffer?

**Comment by borisbrodski** [comment]
Just found out, that my `<c-m>` mappings interfered with your `<cr>` mapping.
Removed it and now everything is working as expected.

Sorry for bothering you!
Thank you very much for the instant help!

**Comment by tpope** [comment]
To address earlier points:

* Line numbers start at 1, so `0,1` isn't a valid line number at all. That's why it's a convenient spot for Fugitive to attach a special behavior. This is more an implementation convenience than a user facing interface, and I only brought it up to narrow down the problem.
* While `git blame` digs into the past to find when a line was added, `git blame --reverse` digs into the future to find where a line was removed. The work-tree version is the default when the line still exists, much like the initially committed version is the fallback when the line has always existed.
* If all you want to do is return to the work-tree version, `:Gedit` is probably a better choice.
