### ISSUE TITLE
FugitiveStatusline() issue

### ISSUE THREAD

**Issue by nkabbara** [tpope/vim-fugitive#1834]
Hi Tim!

I hope all is well.

A recent update is rendering `FugitiveStatusline()` only functional after I use some`:G` Command, so my statusline doesn't show my git branch until after I use fugitive.

To reproduce:
1. Open vim and run `echo FugitiveStatusline()`
2. You'll notice nothing return.s
3. Run something like `:G status`, then run `echo FugitiveStatusline()`
4. You'll notice now it returns git branch info.

Thanks!

**Comment by tpope** [comment]
This is an unsurprising consequence of the recent switch to lazy initialization. Just gotta figure out what's preventing me from reproducing it.

**Comment by dblanken** [comment]
It looks like I was having the same issue while using vim-plug as my plugin manager.  Once I changed back to vim builtin packages, it is working as intended.  I suspect Tim might be using either pathogen or vim packages as well, which is why it could not be reproduced.  Are you using a plugin manager, @nkabbara?  Are you able to try it with just vim packages to see if you have the same result?  I haven't tried any other plugin managers to see if this is really a vim-plug issue, but just reporting my findings.

**Comment by nkabbara** [comment]
Hi @dblanken! After updating to this 6b1d902 it started working as intended again. Thanks @tpope for the fix!

**Comment by dblanken** [comment]
@nkabbara Ah I didn't notice the commit fix.  My apologizes for necro-ing a closed one then.  Yes, thanks @tpope!
