### ISSUE TITLE
Ggrep -q does not open quick fix window

### ISSUE THREAD

**Issue by lzap** [tpope/vim-fugitive#1884]
Hey,

I am on Fedora 35 and I am cleaning up my dated configuration and replacing it with minimalistic version. For some reason, I cannot get `Ggrep -q pattern` working, it simply performs the grep, nothing is shown on the output and them Vim redraws without any change. There is nothing in the quickfix window. Like as this was passing `--quiet` into `git grep` which indeed shows nothing (only returns an exit code).

Is this expected behavior? This is what docs says:

```
:Ggrep[!] --quiet [args]
:Ggrep[!] -q [args]     Like |:Ggrep|, but instead of displaying output, open
                        the quickfix list.
```

Here is my very minimalistic config I am testing this with:

https://lukas.zapletalovi.com/2021/11/a-sane-vim-configuration-for-fedora.html

Thanks!

**Comment by lzap** [comment]
Oooh it is the exclamation mark what does this, not `-q`! Sorry.

Hmmm I am trying to figure out how to map an interactive grep when Vim would ask for a pattern and then it would automatically open quickfix window:

    nnoremap <leader>g :Ggrep! <SPACE>

No idea how to do that, I wish Ggrep had this built-in somehow. Anyway, closing, cheers!

**Comment by lzap** [comment]
For the record, I figured it out! I think I might be also a Vim genius :-)

    nnoremap <leader>g :copen<cr>:Ggrep! <SPACE>

**Comment by tpope** [comment]
> I am on Fedora 35 and I am cleaning up my dated configuration and replacing it with minimalistic version. For some reason, I cannot get `Ggrep -q pattern` working, it simply performs the grep, nothing is shown on the output and them Vim redraws without any change. There is nothing in the quickfix window. Like as this was passing `--quiet` into `git grep` which indeed shows nothing (only returns an exit code).

I can tell you're running an old version because the latest version will not show you an exit code. Try upgrading and start over.

> Oooh it is the exclamation mark what does this, not `-q`! Sorry.

No, the `!` is optional. That's what the brackets mean. The meaning is the same as with `:grep!`: don't jump to the first result.

> For the record, I figured it out! I think I might be also a Vim genius :-)

I hate to be the bearer of bad news, but

> ```
> nnoremap <leader>g :copen<cr>:Ggrep! <SPACE>
> ```

This contains multiple mistakes:

* You're calling `:copen` before adding anything to the quickfix list. This means you'll get an error the first time you call it after starting Vim. You also don't need it per the "upgrade" remark above, but if you did need it, you'd want to call it after, not before.
* Chaining multiple commands together with `:<cr>` is obtuse and prone to weird breakages.  Use `<Bar>`. But also you don't need to do this at all, per the above.
* You're doubling the space at the end by putting `<SPACE>` after a literal space. Delete the space. (And no need to yell, make it `<Space>`.)

**Comment by lzap** [comment]
Damn, too bad this got published on https://opensource.com/article/21/12/vanilla-vim-config - well at least I advertised your plugin I think there might be few remaining Vim users not knowing it.  :-)

I have Fugitive from Fedora 35, definitely not the latest and greatest. Thanks for the pointers, I will read more about `<Bar>`. I noted the double space afterwards, and that `<SPACE>` is totally some copy-paste. Surprisingly, no errors appear when I start my Vim.

Thanks, cheers!
