### ISSUE TITLE
Name fugitive created buffers/files after commands

### ISSUE THREAD

**Issue by rgrinberg** [tpope/vim-fugitive#1919]
I sometimes find myself staring at the output of `:Git diff` and not remembering where exactly this diff came from. Fugitive could be more helpful in figuring this out by setting the buffer name after the command used to generate it.

My vimscript is fairly weak, but I did manage to hack together something that works for me:

```diff
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index 3971b8c..a3bfec7 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -3746,6 +3746,7 @@ function! fugitive#Command(line1, line2, range, bang, mods, arg) abort
     endif
     call extend(env, {'COLUMNS': '' . get(g:, 'fugitive_columns', 80)}, 'keep')
   endif
+  let after_edit = after_edit . ' | file ' .  fnameescape('fugitive ' . join(args, ' '))
   if s:run_jobs
     call extend(env, {'COLUMNS': '' . (&columns - 1)}, 'keep')
     let state.pty = allow_pty && fugitive#CanPty()
```

Perhaps this behavior would be a better default for fugitive?

**Comment by tpope** [comment]
Unfortunately it's not that simple. Vim will treat that argument as a literal file name, which means that `:cd` will rename the buffer, and `:edit` will clear it rather than reload it, because it doesn't exist on disk.

One alternative approach would be to leave the buffer name alone and change the statusline instead. Here's a proof of concept:

```vim
:au User FugitivePager let &l:statusline = ':Git %{join(get(FugitiveResult(@%), "args", []))}'
```

The downside of this approach is it's hard to to the right thing for everyone when custom statuslines are involved, so this is better suited to a vimrc than to Fugitive itself.

See also #1769.
