### ISSUE TITLE
Is there any way to improve Gclog, Gllog or Git log performance?

### ISSUE THREAD

**Issue by coldspark29** [tpope/vim-fugitive#1937]
When working with huge repositories like the kernel, the performace of all three options given above is too slow. Vim freezes for minutes and I have to Ctrl-c my way out of it. There are no issues with !git log though, which I have mapped to <leader> gl for now. But then I have to use the mouse to copy commit numbers etc.

So is there any way to improve performance or is it not normal that it takes that long?

**Comment by coldspark29** [comment]
Could you maybe reduce the number of commits to diplay to say a 100? That would probably make it a bit faster

**Comment by tpope** [comment]
Short answer: The commands `:Gclog`/`:Gllog` are softly deprecated (but no plans to remove them any time soon), and I don't plan on sinking further time into them, but I would merge a change like you propose if it met the following requirements:

* If we go over the limit, add a line to the end of the quickfix indicating as such. For a 255 commit limit, this could be could be accomplished by passing a limit of 256, collecting the first 255 commits, and then adding a message if there's a 256th commit.
* If the user passes a limit like `-500` or `-n 500`, that overrides the implicit limit. That is, `:Gclog -500` should show 500 commits, not 255. There's no need to include the message at the end in this case. (Implementing this will involve iterating over the argument list, and isn't inherently "hard", but but might be a bit much for someone not well versed in VimL.)

`:Git` is a thin wrapper around `git`, and thus `:Git log` is a thin wrapper around `git log`. Adding a special hidden limit is out of the question. I would also point out that it is _much_ faster than `:Gclog`, due to performance characteristics of the quickfix list. Doing a quick and dirty benchmark on 100,000 commits, `:Git log` takes 33 seconds, `:Git log --oneline` takes 4 seconds, and `:Gclog` takes ... 12 minutes.

Finally, I would note that mapping `gl` to `:Git log --oneline -1000` might be good enough for your purposes.

**Comment by tpope** [comment]
Latest version of `syntax/git.vim` highlights it correctly. In Vim proper or https://github.com/tpope/vim-git.

**Comment by coldspark29** [comment]
Thanks! You are godsend

**Comment by kaihowl** [comment]
From profiling I see that due to "-L1,<n>:<file>" in the command invocation, the full content of the file is printed for each revision. Adding `-s` to the command to prevents this.

Is there any reason to have the full contents of the file output for any revision?

**Comment by tpope** [comment]
It does that for the ranged version, because it parses the `@@` lines in the patch output to figure out what line to jump to. If you just want the current file, not part of it, call `:0Gclog` and that argument will be elided.
