### ISSUE TITLE
Large Unpulled section

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1963]
I have a problem when working on a branch in active/big repository – Unpulled section is almost always at 256+ commits limit. This makes it hard to work with the status buffer:

* Sections I care about – Unstaged/Staged and Unpushed – are separated by huge but mostly useless Unpulled
* Visual noise from many commits I don't really care about
* I feel loading displaying these commits makes the status buffer slower

Workarounds I can think of:

* Merge/rebase w/ upstream often. Not always a good option
* Don't fetch often, keep upstream stale. Doesn't work if I work with multiple branches
* Unset upstream branch. Removes Unpushed section which is a no-go
* Use 'fake' local upstream branch. Needs constant manual effort

---

Did I miss any existing workaround? If not, what do you think about these ideas:

* Reduce limit for Unpulled from 256 to 10 displayed commits
* Don't show commits for Unpulled at all
* Make these sections foldable, fold Unpulled by default
* Make Unpulled hideable through configuration (fugitive or git)

**Comment by odnoletkov** [comment]
I'm using `origin/master` as upstream branch for all local branches. This is to see list of local not yet integrated commits. And to occasionally rebase on the recent version.

`push.default` is unset which means it is `simple`. I tried other values too but the only thing affected was `Push: origin/branch` disappears for 'upstream' value – this makes sense. But I don't push at all since integration happens externally (i.e. Github, Phabricator).

**Comment by tpope** [comment]
I guess Git configuration is the least worst option here.

> * Reduce limit for Unpulled from 256 to 10 displayed commits

This just screams "why is this one second special cased" and is basically obligating me to make it configurable anyways.

> * Don't show commits for Unpulled at all

The full list of commits is of medium-low value. But the fact there are commits at all is of high value, and there isn't really a better way to convey that.

> * Make these sections foldable, fold Unpulled by default

Raises questions about what happens when reloading the buffer. Plus see the first point.

> * Make Unpulled hideable through configuration (fugitive or git)

We could have an option like `branch.whatever.fugitiveBlahBlahBlah` to allow for granular specification, and then a top level option that covers the repo and global cases. Perhaps a remote level option too if that's desirable. The problem is the `BlahBlahBlah`. With two unpulled sections, I can't come up with a name that isn't tediously verbose and unambiguous.

I believe Magit uses "Unmerged" for one of these, and I had been contemplating copying that, but that would create an asymmetry with the unpushed side. It might be worth looking into what configuration options Magit provides along these lines and see if we can draw insight from that.

The good news is we could make the option both a Boolean and an integer, covering 2 use cases with 1 stone.

**Comment by tpope** [comment]
> * Sections I care about – Unstaged/Staged and Unpushed – are separated by huge but mostly useless Unpulled

This suggests reordering the sections is worthy of consideration, but I'd have to think that through a bit more. I would also be curious to see what Magit does here. I believe I copied it, but I'm not sure, plus it might have changed. Creating a test repository with all 4 sections is just enough work that I'm going to punt on it for now.

**Comment by tpope** [comment]
Okay, I'm a bit confused here. In 2020 I [changed to show unpulled first](https://github.com/tpope/vim-fugitive/commit/279d56eb478abf0741188f1dad872b5f7fc8e18e), citing Magit. But in 2018, [Magit changed to show unpushed first](https://github.com/magit/magit/commit/15534027f0ec47be467cf0058c2085ecf0fd8504), which is the same behavior it exhibits today. I guess I had fired up an old version? I would be open to going back to the Magit order if you think that would be a net improvement.

**Comment by odnoletkov** [comment]
Great! Yes I think showing Unpushed first (like Magit does it now) would be a net improvement and would solve the case for me.

While we are at it – Magit also has this nice feature where w/o tracking branch it just shows 'Recent commits' section. In my dreams that section would only show 'local' commits, i.e. `git log HEAD --not --remotes` output. Maybe that's too smart, I'd be happy even with dumb `git log -n 10` version. What do you think?

**Comment by tpope** [comment]
I don't like `-n 10`, it's extremely arbitrary, but `--not --remotes` is intriguing, if you want to spike that out.
