### ISSUE TITLE
how to remap ]c to work in inline diffs

### ISSUE THREAD

**Issue by ns740** [tpope/vim-fugitive#1984]
in my .vimrc (but i am using nvim if that matters) i have
```
map ]c ]czz
map [c [czz
```
to center the change when jumping to each change in a `vdiff`
(and it works as expected including in the vdiff triggered by `dv` in the fugitive window)

but when i jump between inline diff hunks using `]c` in the fugitive window, the remap doesn't work (it jumps to the hunk but doesn't center - as if the `zz` is ignored).

why doesn't this do what i expect?   
is there a way to properly remap it?

**Comment by tpope** [comment]
Vim's built-in `[c` and `]c` only work in vimdiff mode. They do nothing in the Fugitive window by default. Fugitive thus _remaps_ them to achieve the desired behavior. These maps also provide custom scroll behavior, but instead of blindly re-centering the cursor line, they scroll "just enough" so the full hunk is visible.

> is there a way to properly remap it?

I haven't tried it (and don't plan to), but I would expect that yes, it is possible.

**Comment by ns740** [comment]
ah i see your point - getting the whole hunk on screen is nice actually.    maybe the "proper" fix here is for me to make the current line easier to find.    thanks
