### ISSUE TITLE
[Feature Request] Have `cF` and family work when on a commit sha in a blame window

### ISSUE THREAD

**Issue by alibby** [tpope/vim-fugitive#2035]
I often want do `cF` on a commit I find using `Gblame`.  But I need to open a `Git log` window and then find the commit and go to it for `cF` to work for the staged changes.

Thanks for all you do.

**Comment by odnoletkov** [comment]
Not exactly solving your issue but – no need to search the log, you can <kbd>\<CR></kbd> in the blame buffer to open commit under cursor and <kbd>cF</kbd> from there

**Comment by tpope** [comment]
This is in line with my long term vision of unifying the various buffer maps as much as possible.

One thing I really don't like about `cF` here in particular is it makes it a bit too easy to accidentally rebase thousands of commits back. But since that's also true of the map in the commit buffer, I guess we can extend that to the blame buffer too, and come up with a solution for both later.
