### ISSUE TITLE
[Feature Request] Fold the sections 

### ISSUE THREAD

**Issue by ray-x** [tpope/vim-fugitive#2111]
I am wondering if the sections in `G` can be folded:
![image](https://user-images.githubusercontent.com/1681295/216807742-37c30874-e31e-4d1e-9074-3d9ae20ec026.png)

One workaround would be add \<Tab> before each items in the list, so I can use `za` to toggle the folding.

Thanks!

Similar feature in other projects:
Folded
![image](https://user-images.githubusercontent.com/1681295/216807794-cbd13921-b7a8-4b07-994c-2fc759bfc08a.png)
Unfolded
![image](https://user-images.githubusercontent.com/1681295/216807817-9bb94cce-d009-43c9-969d-6fb75de906af.png)

**Comment by tpope** [comment]
I would like it on the record that this issue is essentially "I've made a mess of my my untracked files, please add a feature where I can avoid having to look at the mess I made." There are multiple options at your disposal to deal with untracked files that do not involve changing Fugitive:

* Add them to `.git/info/exclude` (perhaps using `gI`).
* Add them to `.gitignore` (perhaps using `1gI`).
* Turn off `status.showUntrackedFiles`.
* Delete them.
* Move them to a location outside the repository.

That said, this is #1317 again, and I will be following up on my proposal there to mark the relevant syntax groups as foldable.

**Comment by kevinhwang91** [comment]
Feel confused about fugitive doesn't `set foldmethod=syntax` and I don't think there is a perf issue for that.

**Comment by kevinhwang91** [comment]
Got it, thanks for your explanation.
