### ISSUE TITLE
GBrowse with range returns sha URL instead of the branch name

### ISSUE THREAD

**Issue by Jendker** [tpope/vim-fugitive#2118]
I have noticed that calling `GBrowse` with range returns URL with commit SHA, while calling it without the range it return URL with a branch name. Is this expected behavior? Is there any way to control if the SHA is dereferenced? I have seen this issue: https://github.com/tpope/vim-fugitive/issues/85 but I'm not sure how to provide the argument correctly to get the expected result.

**Comment by tpope** [comment]
It is expected behavior. A link to a particular line number on a particular branch is incredibly fragile, a simple change to the file will cause the link to point at the _wrong_ line, which can be incredibly confusing. In [2011](https://github.com/tpope/vim-fugitive/issues/85#issuecomment-1398487), I erred on the side of allowing the user to do it anyways if they really wanted to:

>  It is legitimate to want to link directly to the branch as well, so I don't want to remove that option entirely.

I've since changed my mind. The legitimate use cases for creating a fragile link like that are so fringe, it is better not to support it at all.
