### ISSUE TITLE
`:G`: Space saving: "Head", "Merge", "Help" into single line?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tpope/vim-fugitive#2126]
Currently we have this:

```
Head: master
Merge: origin/master
Help: g?

Unstaged (8)
M e2e/shipments.go
M pkg/product/api/mocks/client.go
M service/inventory/reactor/service_carton_aggregate_events.go
```

But we could save space with such layout, if width is enough:

```
Head: master                    Merge: origin/master                                     Help: g?

Unstaged (8)
M e2e/shipments.go
M pkg/product/api/mocks/client.go
M service/inventory/reactor/service_carton_aggregate_events.go
```

**Comment by tpope** [comment]
The headers are interactive; you can press `<CR>` on the `Help` header to open the help, for example. This small space savings breaks that. And what happens if the branch name is really long? Even at 6 characters, the example given won't fit into an 80 column terminal.

Note you can turn off the `Help` header with the `advice.statusHints` Git setting.
