### ISSUE TITLE
Feature request: is it possible to do auto reload?

### ISSUE THREAD

**Issue by kgfly** [tpope/vim-fugitive#2134]
One cool feature of VScode gitlen is that it can do auto reload when the file is modified by external tool.
Eg, 

![image](https://user-images.githubusercontent.com/12282281/225540688-799f8750-046d-470e-860f-7603bdf56971.png)

If the file is modified by external tool, suc has notepad, after a few second, vscode can auto reload the change.

Can vim-fugitive have similar auto reload feature?

People does not have to press ":G" time to time.

Thanks.

**Comment by tpope** [comment]
You can try `let g:fugitive_focus_gained = 1`. If you switch to notepad and change a file, this will cause it to reload when you switch back. It's off by default on Windows because Windows is slow.

Fugitive will also auto-reload under other circumstances, such as saving a file within Vim. One thing it can't do is monitor the file system for changes. Vim has no APIs for that.
