### ISSUE TITLE
Restore window sizes after `:Git blame`

### ISSUE THREAD

**Issue by flipsi** [tpope/vim-fugitive#2203]
## Oberved behavior

When having multiple (equally sized) vertical windows open... 
* then executing `:Git blame`,
* then closing the blame window,

I end up with a different (non-equally sized) window layout.

## Expected behavior

I would expect to end up with the original (if not possible with an equally-sized) window layout.

## Questions

* Is my expectation flawed somehow or could this be considered a bug? 
* Is restoring the original window layout ouf of scope for this plugin? 
* If yes, what would be a recommendable workaround? I tried something along the lines with `au WinClosed *.fugitiveblame wincmd =` but had no success.

**Comment by tpope** [comment]
> ## Questions
> * Is my expectation flawed somehow or could this be considered a bug?

Vim's default behavior is to enable the option `'equalalways'`, which takes care of this automatically. If you've turned off that option, Fugitive doesn't do anything to compensate.

> * Is restoring the original window layout ouf of scope for this plugin?

Probably. What happens if another window was opened or closed in the interim? It's hard to solve this robustly.

> * If yes, what would be a recommendable workaround? I tried something along the lines with `au WinClosed *.fugitiveblame wincmd =` but had no success.

`WinClosed` is documented as acting on the window ID, not the buffer name, and firing before the window is closed, not after. You could try to compensate for that by checking `bufname(buwinbufnr(expand('<amatch>')))`, and finding some way to defer the operation, such as setting a variable and checking for it in `WinEnter`. Or you might have better luck using a different autocommand, like `BufDelete`.
