### ISSUE TITLE
 Conflict with gitsigns.nvim when staging a hunk

### ISSUE THREAD

**Issue by m-demare** [tpope/vim-fugitive#2238]
I originally reported this to gitsigns (https://github.com/lewis6991/gitsigns.nvim/issues/916), but was told it wasn't a gitsigns issue. I don't know if it's a fugitive issue or if it's caused by nvim's diff, so do tell me if this belongs somewhere else

The issue is the following: when I'm viewing a diff in fugitive, and I stage a hunk with gitsigns, the colours on all windows glitch out. The only way to fix them is to close the diff windows

Nvim version: NVIM v0.9.4 Build type: Release LuaJIT 2.1.1699392533

Before stage:
![283887763-3c69f034-81c3-4552-becb-4ff0d8b88526](https://github.com/tpope/vim-fugitive/assets/34817965/a958be87-8833-428d-bd04-ef6d3f7cbf03)

![283887805-f712b0ed-4343-4083-ab0d-73bef796f83a](https://github.com/tpope/vim-fugitive/assets/34817965/e2e73cf7-054b-44b9-aeaf-b838c2c05828)

### Minimal config

```Lua
for name, url in pairs{
    gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
    fugitive = 'https://github.com/tpope/vim-fugitive',
} do
    local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
    if vim.fn.isdirectory(install_path) == 0 then
        vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
    end
    vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
    debug_mode = true,
    on_attach = function(bufnr)
        local gs = package.loaded.gitsigns
        vim.keymap.set('n', '<leader>hs', gs.stage_hunk, { buffer = bufnr, silent = true })
    end
}
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Open fugitive with :G
3. Use `dv` on an unstaged file to open diff
4. Use `<leader>hs` on a hunk to stage it

**Comment by tpope** [comment]
The reason the highlighting is getting screwed up is because the option `diff` is being set in the status window, causing all 3 to be diffed. When I check `verbose set diff?` in the status window after the fact I see this:

```
  diff                                                                                                                                                                                
        Last set from Lua
```

So what is happening is that you're invoking `stage_hunk` from gitsigns.nvim, which is written in Lua, and then some Lua code is setting an option that screws up the highlighting.

Fugitive has no Lua code. Meanwhile, have a look at this [Lua code from gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim/blob/5fc573f2d2a49aec74dd6dc977e8b137429d1897/lua/gitsigns/diffthis.lua#L202-L215):

```lua
  for _, w in ipairs(api.nvim_list_wins()) do
    if api.nvim_win_is_valid(w) then
      local b = api.nvim_win_get_buf(w)
      local bname = api.nvim_buf_get_name(b)
      if bname == bufname or vim.startswith(bname, 'fugitive://') then
        if should_reload(b) then
          api.nvim_buf_call(b, function()
            vim.cmd.doautocmd('BufReadCmd')
            vim.cmd.diffthis()
          end)
        end
      end
    end
```

Note in particular the check for `vim.startswith(bname, 'fugitive://')` (which matches the status window) and the invocation of ` vim.cmd.diffthis()` (which turns on the `diff` option).

This is very straightforwardly 100% a Gitsigns issue.

**Comment by m-demare** [comment]
Thanks for pointing me in the right direction!
I'll try to fix it and send a PR to gitsigns

**Comment by tpope** [comment]
You might find `vim.fn.FugitiveParse(bname)` helpful. Try `:echo FugitiveParse(bufname())` in each of the `fugitive://` buffers to see how it works.
