### ISSUE TITLE
`:Git blame` output is misaligned when LSPSaga Breadcrumbs are enabled

### ISSUE THREAD

**Issue by amcooper** [tpope/vim-fugitive#2241]
I'm using both the [vim-fugitive](https://github.com/tpope/vim-fugitive) and [LSPSaga](https://github.com/nvimdev/lspsaga.nvim) plugins for Neovim. The Breadcrumbs module of the latter does not play nicely with the `:Git blame` command of the former. Basically vim-fugitive is unaware of the extra line slipped in by LSPSaga Breadcrumbs, and the blame line is rendered misaligned from its associated line of code. I've included a screenshot below to illustrate.

I'm posting the same issue at LSPSaga, as I don't know what the best place to tackle this would be.

![misaligned-blame](https://github.com/tpope/vim-fugitive/assets/2553540/f08e46db-8c38-46fa-9e92-2913ebd33adb)

**Comment by tpope** [comment]
Fugitive uses `:set scrollbind` to keep the 2 buffers aligned. I don't know what Neovim API is being used to create these so-called breadcrumbs, but it sounds like it has a bug or a limitation in how it interacts with `scrollbind`. I don't think there's anything Fugitive can do. LSPSaga could maybe work around this limitation (e.g., by creating a dummy breadcrumb in *all* windows), or maybe it could be fixed in Neovim itself.
