### ISSUE TITLE
What git command, if any, does inline diff call?

### ISSUE THREAD

**Issue by hahuang65** [tpope/vim-fugitive#2249]
I'm trying to integrate https://dandavison.github.io/delta/ into git, such that fugitive uses it everywhere that it can.

However, I don't think that inline diffs is using it (pressing `=` on a file in the `:Git status` window.)

What command do the inline diff keys use to bring up the diff?

**Comment by tpope** [comment]
They use `git diff --no-color`, because the color is provided by Vim's syntax highlighting. `delta` uses ANSI escape sequences to provide highlighting, which Vim does not support, except in terminal buffers. So the closest you can get to `delta` support in Vim is to use a command that runs in a terminal. Here's one:

```
:Git -c pager.diff=delta diff
```

**Comment by hahuang65** [comment]
Got it, thank you, that makes sense.
