### ISSUE TITLE
Use winfixbuf in nvim for specific propouse windows 

### ISSUE THREAD

**Issue by leiserfg** [tpope/vim-fugitive#2272]
[This](https://github.com/neovim/neovim/issues/12517) was just merged in nvim and will fix  the issue of accidentally opening files in the `:G blame` or `:G`   windows.

**Comment by tpope** [comment]
This option may be too aggressive. It prevents reloading the window by calling `:e` with no arguments. That doesn't change what buffer the window points to, but it is nonetheless blocked.

The first complaint from a user has also landed at https://github.com/tpope/vim-fugitive/discussions/2275.

I'm leaning strongly towards rolling back the status buffer change, and only enabling it for blame buffers.

**Comment by ColinKennedy** [comment]
Hey folks, my bad, I thought I handled the "if no args for edit or edit is given the current buffer, allow" this case. It's a bug that I'll fix and patch into Vim

**Comment by heymatthew** [comment]
+1 for only scoping just to blame buffers.

I intentionally open windows on top of `:G` and treat it as another split. My workaround to keep this workflow is:
```
" Workaround: Allows other content to load on top of :Git pane
autocmd BufEnter * if &filetype == 'fugitive' | set nowinfixbuf | endif
```

But if it's just me then I'm happy to leave my hack in place ;-).

![hold spacebar](https://github.com/tpope/vim-fugitive/assets/45738/e0779758-d284-427d-8547-5742f76bedeb)

**Comment by tpope** [comment]
> I intentionally open windows on top of :G and treat it as another split.

You may want to use `:Gsplit :` or `:Gedit :`. which opens the status buffer _without_ any special window behavior.

**Comment by heymatthew** [comment]
The old behaviour was closer to how `:h` behaves because it reuse or warp to the window. After reading docs I also sometimes load another buffer on top. The suggested commands are great, but I do want some of that behaviour.

I really lean into it by defining a custom map:

```
" git status
nnoremap gs :vert G<CR>
```

Knowing I can bring `:G` back easily I open stuff on top frequently. But I also do just leave it like with `:h` to refer to while I work.

I don't mind if you want to keep this behaviour, I can work around it. I just never accidentally open files (as suggested by this issue). Even if I did I'd just `CTRL-o` to get back.

**Comment by tpope** [comment]
I't not just to prevent accidents. It prevents some other operations (such as selecting an entry from the quickfix list) from using that window.
