### ISSUE TITLE
remove untracked file / folder

### ISSUE THREAD

**Issue by rweng** [tpope/vim-fugitive#23]
When I am in Gstatus, is there a way to delete an untracked file/folder? :Gremove is only for files tracked by git, as far as I see it. If there is no way, this is definitively a feature request. If there is, I would appreciate if you could put it in the docs :)

Thanks for this awesome git wrapper!

**Comment by Rom1deTroyes** [comment]
Just a note, because we are vimist, and I like archeology ... You can also do it by :
- placing the cursor on the filename
- press `.` to have a : command line pre-populated with the filename
- type `!rm`to have the command line ready to remove you file.

It's 4 keystrokes, and no finger contortion :crossed_fingers: 

(BTW thanx for all your work, it's amazing !)

**Comment by tpope** [comment]
Deleting an untracked file is supported on `X` now.
