### ISSUE TITLE
G(v)diffsplit issue(?)

### ISSUE THREAD

**Issue by componhead** [tpope/vim-fugitive#2317]
Hi. Why the choice to ignore `splitright` and `splitbelow` vim option?
From the manual:
```
                                                *:Gdiffsplit*
:Gdiffsplit [object]    Perform a |vimdiff| against the given file, or if a
                        commit is given, the current file in that commit.
                        With no argument, the version in the index or work
                        tree is used, AND THE WORK TREE VERSION IS ALWAYS
                        PLACED TO THE RIGHT OR BOTTOM, depending on available
                        width.  Use Vim's |do| and |dp| to stage and unstage
                        changes.

```
thank you

**Comment by tpope** [comment]
The original reason was for a consistent user experience. Regardless of whether you start `:Gdiffsplit` from an old buffer or a new buffer, the end result is the same.

I've since decided that matching the behavior of the vanilla `:diffsplit` is more important, so the modern reason is for backwards compatibility. As a compromise, the behavior was narrowed to the "no argument" case, which means it's extremely easy to bypass with `:Gdiffsplit %` for example if you don't want it.
