### ISSUE TITLE
help fugitive

### ISSUE THREAD

**Issue by goog** [tpope/vim-fugitive#249]
when I type "help fugitive" , the terminator displays E149: Sorry, no help for fugitive
how to generate help tags ?

**Comment by JasonMFry** [comment]
I was having trouble with this, too. For some reason the command listed in the readme `vim -u NONE -c "helptags fugitive/doc" -c q` wasn't helping. I use nvim so I also tried `nvim -u NONE -c "helptags fugitive/doc" -c q` and that didn't help. Note that `fugitive/docs` is the directory so make sure you point it to the right spot.

Finally, I did `:helptags ALL` which, according to `:h helptags`, 

> Generate the help tags file(s) for directory {dir}.
When {dir} is ALL then all "doc" directories in
'runtimepath' will be used.

And that worked. I hope I didn't ruin other helptags as a result though.

**Comment by praton1729** [comment]
The clone command in the README clones the repo in a folder named fugitive since it is not the standard clone URL you generally pick up from the repo for cloning. You need to replace the "fugitive/doc" with "vim-fugitive/doc" if you use the standard URL and don't provide the folder name while cloning.
