### ISSUE TITLE
Use :Dispatch if available.

### ISSUE THREAD

**Issue by nocksock** [tpope/vim-fugitive#450]
It'd be great if commands like `:Git push` would be using `vim-dispatch` if it's available. Or provide an easy way to enable it config-wise.

**Comment by nv-quan** [comment]
What about :Gclog? Normally with a big code base this command takes a very long time. I'm talking about use cases like finding a commit with Gclog --grep.

**Comment by tpope** [comment]
Problem there is that if you don't pass an option like `--grep`, the CPU is the bottleneck, and making that async changes things from "Vim blocks for several seconds" to "Vim looks like it's broken for several seconds". Plus the number of seconds increases due to increased overhead.

Bigger problem is that `:Gclog` sucks because the quickfix list sucks (that's where most of the CPU is going), and it's all but deprecated at this point. Trying to improve it is a real "rearranging deck chairs on the titanic" situation. If anything's getting async, it's `:Git log`.

**Comment by mosheavni** [comment]
For anyone coming from google, `fugitive` has its own asynchronous mechanism now by just calling the `Git` command with bang (`!`),
Example:

```
:Git! push
```
