### ISSUE TITLE
error in dp: fatal: corrupt patch at line N

### ISSUE THREAD

**Issue by ainformatico** [tpope/vim-fugitive#551]
Steps:
1. `:Gstatus`
2. `dp`

Then it pops up this:

```
diff --git a/Guardfile b/Guardfile
index eaa333c..274c1be 100644
--- a/Guardfile
+++ b/Guardfile
@@ -3,6 +3,7 @@

 guard :rspec, cmd: 'bundle exec rspec' do
   watch(%r{^spec/.+_spec\.rb$})
+  watch(%r{^lib/featurer/adapters/redis.rb$})     { 'spec/lib/featurer_spec.rb' }
   watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
   watch('spec/spec_helper.rb')  { 'spec' }
 end
```

I edit to make it:

```
diff --git a/Guardfile b/Guardfile
index eaa333c..274c1be 100644
--- a/Guardfile
+++ b/Guardfile
@@ -3,6 +3,7 @@

 guard :rspec, cmd: 'bundle exec rspec' do
   watch(%r{^spec/.+_spec\.rb$})
   watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
   watch('spec/spec_helper.rb')  { 'spec' }
 end
```
1. `:Gw`

Then it raises this error:

```
fatal: corrupt patch at line 12
```

Environment:
- Macvim/vim 7.4
- Git 2.0.4

**Comment by mikkorantalainen** [comment]
> @@ -41,14 +41,17 @@ module Featurer

You cannot edit patches without adjusting the header. The above header says that 14 lines starting on line 41 should be replaced with 17 lines. However, you did edit the patch to only output 16 lines because you removed the line that you no longer want to have and the actual output of that patch is 16 lines. Because 16 != 17, the patch is considered corrupt.

In fact, git allows this style of modifying patches and if you do `git apply --recount` it will work. In that case if the patch lines do not match the header lines, the header lines are considered incorrect and best effort matching will be  used instead. You should inspect the results manually if you use this flag.

**Comment by tpope** [comment]
I largely consider this feature deprecated in favor of inline patching, but I would be okay with automatically using `--recount`.
