### ISSUE TITLE
Cannot see file after Glog --follow

### ISSUE THREAD

**Issue by elmart** [tpope/vim-fugitive#563]
Glog was not showing some commits for a file, then I realized the commits I wanted were from a time the file had a different name. Then I used `Glog --follow` and got a nice list of commits, but when I try to open a revision from a time before the current file name, I get this:

```
Error detected while processing BufReadCmd Auto commands for "fugitive://**//[0-9a-f][0-9a-f]*":                   
fugitive: rev-parse 6f53cb1cc311025f0c21d142af06fbfbda113fc4:src/nvim/memfile.c: fatal: Needed a single revision
```

**Comment by jeffvandyke** [comment]
I'm noticing this while working on a project that moved a bunch of files around... bumping into a lot of edge cases with using `--follow` behavior. In fact, since git made log.follow a config option, I've enabled it just for working with this project.

I've been informed that `git log --follow` works by changing what file path its looking for when it sees that a rename happened for a file change, so it seems like :Glog could do something similar. Not sure if it's time for me to learn vimscript or not...
