### ISSUE TITLE
Make Gdiff window while rebasing a little bit more intelligible

### ISSUE THREAD

**Issue by mcepl** [tpope/vim-fugitive#613]
When using git mergetool (where I use fugitive for diffing) I get this:

![screenshot from 2015-02-27 13 42 17](https://cloud.githubusercontent.com/assets/198999/6412626/97a271b0-be86-11e4-8209-bc3b877269d4.png)

I am sorry, but the difference between `<///home/matej/archiv/knihovna/repos/bitlbee/.git//2/lib/misc.c 1,1` and `<///home/matej/archiv/knihovna/repos/bitlbee/.git//3/lib/misc.c 1,3` is not very illuminating. Could we get something more reasonable (e.g., name of the branch where the particular version comes from, or something)?

**Comment by tpope** [comment]
I don't know of a good way to get the branch name, but `FugitiveStatusline()` contains that `2`/`3` (ours/theirs) in a more readable form. There's also `FugitiveReal()` to get a more readable filename rather than that ugly `fugitive://` URL. Some plugins like Flagship and Airline hook this up automatically.
