### ISSUE TITLE
Changing mappings provided by fugitive

### ISSUE THREAD

**Issue by ghost** [tpope/vim-fugitive#647]
I'm using a [weird keyboard layout](http://adnw.de) which has DTRN where less wacky keyboards have HJKL. This gets in the way of a lot of things, most of which I'm able to fix.

What I wasn't able to fix were the keybindings in the `:Gstatus` window, specifically the `r` mapping. I've tried overwriting the mapping in `after/ftplugin/gitcommit.vim`, but since the mappings [seem to be defined after the filetype of the `:Gstatus` window is set](https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L2446), they just get overwritten.

Would it be alright if I submitted a PR that extends [`g:fugitive_no_maps`](https://github.com/tpope/vim-fugitive/pull/604) so that there aren't any mappings at all, similar to your other plugins?

(In any case, fugitive is awesome. Thanks for writing it. :+1:)

**Comment by tpope** [comment]
I'd rather just set the filetype afterwards, if that would help. I can't imagine most `g:fugitive_no_maps` users wanting to completely break `:Gstatus`.

**Comment by robodendron** [comment]
Hmm… I just noticed that both the commit window and the status window have `filetype=gitcommit`, so it wouldn't be enough to just change the order and overwrite keybindings: Both windows would then get those keybindings, even though they handle fundamentally differently.

I suppose one way to solve this would be to use different filetypes for different windows. (Feels cleaner to me too instead of setting everything in `fugitive.vim`, but that's not my call to make.)

On the one hand, this seems like a major refactoring effort for what amounts to a single keybinding on my end. On the other, it would allow us to set the keybindings for *all* git buffers ourselves, which sounds like a good idea to me.

**Comment by tpope** [comment]
You can check `&modifiable` to determine if it is a status window or commit message.

**Comment by robodendron** [comment]
Right, didn't even occur to me. Alright then, changing the order should be enough. :)

**Comment by tpope** [comment]
Easiest route is probably to put the upcoming filetype in a variable rather than setting it directly, then officially assign it near the end of the function.

**Comment by Sathors** [comment]
I am exactly in the same position than @robodendron (funky layout), meaning that my CTSR is actually remapped to HJKL.

I haven't found how to remap successfully the r key though.

I have tried putting in the after/ftplugin/gitcommit.vim the following lines:
nnoremap <buffer> <silent> r l
nnoremap <buffer> <silent> l :<C-U>edit<CR>

But it is not working, because it seems that the mapping in the plugin is executed after the filetype has been set. 
How could I change the mapping without touching the vim-fugitive files directly?

Thanks

**Comment by tpope** [comment]
See https://github.com/tpope/vim-fugitive/issues/1080#issuecomment-521100430
