### ISSUE TITLE
"E21: Cannot make changes, 'modifiable' is off" when typing cc in the preview window

### ISSUE THREAD

**Issue by h3xx** [tpope/vim-fugitive#684]
I've found that typing <kbd>c</kbd> [pause] <kbd>c</kbd> in the :Gstatus window causes the <kbd>cc</kbd> key command to execute, which gives the E21 error because it refuses to modify the buffer marked read-only.

Additional information:

In the environment I tested in, `&timeout` is 1, `&ttimeout` is 0. `&timeoutlen` is 1000 and `&ttimeoutlen` is -1. 

I have verified this behavior in a clean-room environment with just this plugin installed.

**Comment by tpope** [comment]
Sounds like the expected behavior for those options. You have a 1 second timeout.

**Comment by Andrikin** [comment]
I started to play with fugitive, and man, it fells good! But I'm facing E21 messages when trying to save a commit using i_CTRL-O command. It's not a big deal, since fugitive's commands work flawless in normal mode, but I have this bad habit to <c-o>ZZ files, which is triggering this error.

**Comment by Andrikin** [comment]
When in insert mode, to quickly ZZ the commit. I'm using s to stage and cc to commit.

**Comment by tpope** [comment]
Okay, so `<Esc>ZZ` (or `<C-[>ZZ`, or `<C-C>ZZ`) is exactly as quick as `<C-O>ZZ` and doesn't leave you in insert mode in another buffer. Feels like you are going out of your way to make things difficult for yourself.

**Comment by Andrikin** [comment]
I know, haha! But my notebook has pt-BR ABNT2 keyboard layout, without the right CTRL. Use <c-c> is to hard with one hand. <esc> reminds me a panic button, used only at moment of crisis, haha. Between <c-[> and <c-o>, the last is too confortable. I know that I created a bad habit using <c-o>ZZ or <c-o>ZQ to quit files. It's only because I got surprise getting E21 error using <c-o>ZZ to quit the commit file.
