### ISSUE TITLE
:Ggrep with submodules

### ISSUE THREAD

**Issue by phmarek** [tpope/vim-fugitive#685]
I've got a few checkouts that use submodules. Now `:Ggrep` has the problem that only the git checkout of the current file is searched, instead of all the git checkouts.

Perhaps there should be a test whether the current file is "just" in a submodule, and if it is, the git "root" should be used for the "git grep" and an additional "git submodule foreach --recursive grep" should be run (but see http://blog.endpoint.com/2010/04/make-git-grep-recurse-into-submodules.html).

**Comment by tpope** [comment]
This sounds like a problem that I don't want to take ownership of.

**Comment by jeaye** [comment]
I would love to have a `:Grgrep`, for recursive grep, within vim-fugitive. @tpope, are you opposed to having this new grep (not changing any existing greps)?

**Comment by tpope** [comment]
So it would grep submodules but *not* the main repo? That sounds ... odd.

**Comment by jeaye** [comment]
On Fri, Mar 18, 2016 at 11:22:11AM -0700, Tim Pope wrote:
> So it would grep submodules but *not* the main repo? That sounds ... odd.

You're right; it should grep both and concatenate the results.

**Comment by tpope** [comment]
Show me a proof of concept I guess, because my hunch is there's at least half a dozen problems doing this you haven't even considered. That `"git grep ...; true"` hack isn't portable for example.

I think a more reasonable goal would be making it easier to compose your own command, perhaps by exposing the rewrite logic that happens afterwards.  Then whatever good-enough hack you come up with could leverage that.

**Comment by odnoletkov** [comment]
git grep now supports --recurse-submodules (as do many other commands). So :Ggrep --recurse-submodules works as expected and there is even autocompletion for this option. There is also a git config option for that. So I guess this is resolved.
