### ISSUE TITLE
But with `Gcommit --amend`

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-fugitive#723]
Hey,

I did a quick search and didn't find this anywhere so want to raise something I found to be rather odd.

When on the `:Gstatus` window, I do a `ca` (which is equivalent to `:Gcommit --amend`) the commit window opens correctly, however if I were to try to cancel this operation with a `:q!` it doesn't do so and ends up committing anyways.

This is potentially dangerous, kindly let me know what you think.

**Comment by tpope** [comment]
How is this different from `git commit --amend` outside of Vim?

**Comment by dhruvasagar** [comment]
I don't believe I ever tried, lol. I am guessing it does as described in this bug, if so perhaps it's a bug with git ? What do you think ?

**Comment by dhruvasagar** [comment]
Yes I just tried, it does save even if I quit without saving the message. Seems slightly odd to me. Not a huge problem though.

**Comment by wookayin** [comment]
FYI: When we use `git commit --amend` outside of vim, use `:cq` (exit vim with a non-zero code) will abort the commit, but in `:Gcommit --amend` it won't (the amend commit happens).

**Comment by tpope** [comment]
You can delete the commit message (`:%d`) to achieve the same effect.

**Comment by gauteh** [comment]
When editing as `git commit --amend` from cmd line just doing `:cq` is very useful. But in the fugitive world you can only achieve this through `:%d` as you point out. Would it be more intuitive to cancel the amend / commit by doing `C-w-c`? Would that be possible to detect as opposed to a regular `:wq`?

If not; maybe `q` like in `:Gstatus` (`:bdelete` also causes the commit to go through). Doing `:cq` will in many cases just close down vim altogether which is a bit overkill.

**Comment by tpope** [comment]
You could certainly remap `<C-W>c`, but I'm not really convinced that's "more intuitive".

I don't really want to map `q` because its default behavior of recording macros is plausibly useful here.

Most editors don't have a `:cq` equivalent, so for all intents and purposes "empty the file and save it" really is the official Git way of canceling a commit. I think it's good enough.

**Comment by gauteh** [comment]
First, I certainly respect your decision on not extending git behavior here. `:%da` is not really difficult to type (or re-map!).  I also agree that `q` is a bad choice, and probably `<C-W>c` as well. 

I do think however that `emptying the file, then save and quit` is not very intuitive. And even though it is the Git way I'd vote for 'fixing' that ;) Reverting a faulty `git commit --amend` is a lot trickier than resetting after a `git commit`.

**Comment by odnoletkov** [comment]
> Reverting a faulty `git commit --amend` is a lot trickier than resetting after a `git commit`.

It's not really tricky with `git reset --soft @{1}`

I actually suffer from a different problem – I often `:cq` out of habit from `:Gcommit` loosing the Vim session… Maybe if there was a separate `:Gcancel` I could teach myself to use it instead of `:cq`. I agree that emptying and saving a buffer is a very awkward way to cancel.
