### ISSUE TITLE
Gcommit does not abort commit message if prepare-commit-msg or commit-msg hooks are found

### ISSUE THREAD

**Issue by oz123** [tpope/vim-fugitive#757]
Hi, 

I have `prepare-commit-msg` and `commit-msg` hooks active. This simply messes up Gcommit. 

Example:

```
#!/bin/bash

if [ -z "`head -n 1 $1`"] ; then
   echo "Aborting due to empty commit message"
   exit 1
fi

BRANCH=`git branch | grep '^\*' | cut -b3- | grep _`
echo $BRANCH
if [ -n "${BRANCH}" ]; then
   TICKET=`git branch | grep '^\*' | cut -b3- | cut -d _ -f 1`
   echo "${TICKET}: $(<$1)" > $1
fi
```

Which works fine. Ticket numbers are prepended to commit titles. Or when no write is done (e.g. I close VIM with q!) the commit is aborted. 

With Gcommit it's a whole new story, here is how it looks:

```
commit 42cbf41f1f79ed74c442e7e1c1eeb05bef53372e
Author: Oz N Tiram <nahumoz@gmail.com>
Date:   Wed Mar 2 12:42:20 2016 +0100

    T-196: # Please enter the commit message for your changes. Lines starting

```

May I also add `vim-fugitive` is awesome, but Gcommit has some issues...

**Comment by tpope** [comment]
Under the hood, Fugitive invokes the following command to commit after the message edit window is closed:

    git commit --cleanup=strip -F <msgfile>

When running this command, Git performs the following 4 steps to prepare the commit message:

* Strips whitespace
* Runs the `prepare-commit-msg` hook
* Runs the `commit-msg` hook
* Strips comments

This means when you leave the message blank, the hook receives a message file with a comment on the first line.

The bug is in your hook not handling this `git commit` usage, not in Fugitive. You can fix it by changing the guard at the top to look for a comment in addition to an empty line:

```sh
case `head -1 "$1"` in
  ''|'#'*) exit 0 ;;
esac
```

This doesn't support a custom `commentChar`, I leave that to you to handle if necessary.
