### ISSUE TITLE
:Ge and friends act strangely when work dir is separate from git dir

### ISSUE THREAD

**Issue by h3xx** [tpope/vim-fugitive#776]
## Symptoms:

When operating on files in a git repo where the working directory is separate from the git directory, some commands act strangely.
- `:Gw` fails with `fugitive: cannot determine file path`
- `:Ge` opens the parent directory of the git directory in netrw
-  `:Gvdiff` fails with `"[parent dir of git dir]" Illegal file name`
- `:Glog` successfully loads the history into the quickfix buffer, but closes the file buffer, instead showing a commit as if I had typed <kbd>cc</kbd>. Pressing <kbd>Enter</kbd> in the quickfix window updates the commit buffer, but does not show the file at that revision.
- `:Gstatus` shows correct working directory status, but pressing <kbd>D</kbd> over a modified file shows no differences. Pressing <kbd>Enter</kbd> opens the file in the git dir's parent directory (NOT the work dir).
## Steps to Reproduce:
1. Use the following shell commands to setup an environment:
   
   mkdir TEMP
   cd TEMP
   git clone git://github.com/tpope/vim-fugitive.git
   mkdir workdir
   cd workdir
   git init --separate-git-dir ../vim-fugitive/.git
   git checkout .
   echo 'changed line' >>README.markdown
2. Open README.markdown in vim.
3. Attempt to run any of the commands listed.
## Version information:
- vim-fugitive 57afba5bdd49b59d57485f90aa0cf3f3a6c47f63 (2016-03-23)
- vim 7.4 (patches 1-1530)
- git 2.8.0 (all git commands work as expected in working directory)

Verified under a clean-room setting with only vim-fugitive installed.

**Comment by tpope** [comment]
Can confirm all if this.

**Comment by systemmonkey42** [comment]
I just chased down a similar problem, this time with 'Ggrep' reporting `fugitive: no work tree`.

calling `git config --add core.worktree $(pwd)`

seemed to calm it down.   Even though there is a file called '.git' with a 'gitdir:' link, it can't (or wont) locate the work tree.

This, of course, doesn't help if I want to maintain multiple work tree's.   Git grep will find .git, identify the incorrect work tree, and probably not do the Right Thing ™

**Comment by h3xx** [comment]
Strangely, fugitive seems to be able to find everything and operate normally when in a submodule of a project with a separate git dir.

I.e. the superproject is like the one I described, and it has a submodule that's cloned using `submodule update --init`. When working on files in that submodule, fugutive works just fine.

**Comment by systemmonkey42** [comment]
Fugitive locates the git-dir and the work-tree by scanning the current folder and parents for a '.git',   If it finds a directory (as in the submodule in your case) it assumes this is the valid work tree, and the '.git' directory is the git dir.   If '.git' is a file, it manually parses it to find `gitdir: `, then opens `$git_dir/config` directly, and parses it to find the worktree config value.   If it used `git rev-parse` with `--git-dir` and `--show-toplevel` it would work all the time, at the cost of calling `git`.

**Comment by ViKomprenas** [comment]
This has been standing for a while. What's the downside in calling `git rev-parse`, exactly? Performance? The git dir is already being cached, I can't imagine it's that bad. Not to mention this _is_ a git wrapper -- why redo their work?

**Comment by tpope** [comment]
`git --git-dir=... rev-parse --top-level` always prints the current working directory, it's worthless.

The problem is that two different work trees share an identical git dir, and all Fugitive tracks is the git dir, so it's fundamentally ambiguous. We should instead track `.git` in the root of the repository, regardless of whether it's the actual git dir or just a file.

Now that we have `git worktree` (which Fugitive supports just fine), can anyone name a good reason to do this low level `--separate-work-dir` stuff? I'm not convinced this is worth prioritizing if not.

**Comment by ViKomprenas** [comment]
Wait, maybe I'm on the wrong bug here. The issue I'm having, which I thought was this or close enough to be a duplicate, was that fugitive breaks when used in a repository created with `git init --separate-git-dir`. Is that separate from this?

Assuming not: why not just call `git rev-parse --top-level` without the `--git-dir` option? That looks like it works fine, but I only did a cursory test.

**Comment by tpope** [comment]
Correct issue, I just don't understand *why* you would call `git init --separate-git-dir` when `git worktree` does basically the same thing but better.

The problem isn't how to find the top level: `git rev-parse --top-level` does work (if called from the right directory) but we can achieve the same results without it. The problem is that the code is structured in a way that we would need to it do it every single time we need the work tree, and we need the work tree a lot (including potentially every time the statusline updates), and that would have very bad performance characteristics.

The solution I proposed of tracking `.git` rather than the actual Git dir location would make it trivial to cache, because now there's a one-to-one mapping of `b:git_dir` to work trees.

**Comment by ViKomprenas** [comment]
[Per the docs:](https://git-scm.com/docs/git-worktree)

> With `git worktree add` a new working tree is associated with the repository. This new working tree is called a "linked working tree" as opposed to the "main working tree" prepared by `git init` or `git clone`. A repository has one main working tree (if it’s not a bare repository) and zero or more linked working trees. When you are done with a linked working tree, remove it with `git worktree remove`.

I only have one working tree, so I used `--separate-git-dir` rather than `worktree add`. (Just trust me that this makes sense in my case, please. I don't have time to explain it and honestly I only half-remember the reason. But everything other than fugitive works fine.)

Anyway, sorry, I misread the code somewhere and thought that was what you were already doing. Carry on.

**Comment by tpope** [comment]
If you do have a one-to-one relation, you can do `git config core.worktree $(pwd)` from the work tree root and Fugitive will pick that up.

**Comment by tpope** [comment]
Now that I think about it, the original example with two work trees for one Git dir is fundamentally unusable. If you `git commit` in one work tree, the other work tree becomes out of sync with `HEAD`. Fugitive failing is the least of your problems.

For the one-to-one case, set `core.worktree`. This is the best practice anyways, as I understand it. If someone wants to investigate making Fugitive smarter in its absence, be my guest, but I'm not too worried about it.

**Comment by ViKomprenas** [comment]
Each work tree gets its own HEAD. https://git-scm.com/docs/git-worktree#_refs

**Comment by tpope** [comment]
Yep, and this is supported by Fugitive, because `git-worktree` sets `core.worktree`.
