### ISSUE TITLE
RFE: support for the interactive rebase

### ISSUE THREAD

**Issue by mcepl** [tpope/vim-fugitive#797]
I need to reorganize a huge branch with plenty of commits on many files (porting of `M2Crypto` to Python 3) and in the end in order to make it at least some order in it, I exploded each large commits touching many files with this script (called `git-split-by-file`):

``` sh
#!/bin/sh                                                                       
set -xeu                                                                        

if [ $# -gt 0 ] ; then                                                          
    MSG=$(cat "$1")                                                             
else                                                                            
    if [ -f ".git/rebase-merge/message" ] ; then                                
                MSG=$(cat .git/rebase-merge/message)                            
        else                                                                    
                read -e -p "Enter the merge commit message: " MSG               
                if [ -z "$MSG" ] ; then                                         
                        exit 1                                                  
                fi                                                              
    fi                                                                          
fi                                                                              

function add_one_file () {                                                      
    FILE="$1"                                                                   
    git add "$FILE"                                                             
    echo -n "$FILE: ${MSG}"|git commit -F -                                     
}                                                                               

git reset HEAD~                                                                 
for f in $(git diff |lsdiff --strip 1) ; do                                     
    add_one_file "$f"                                                           
done
```

So, splitting is not a problem, but now I have a branch with not 40, but 120 commits. I have cut it down back to 50 by combining commits touching one file into one, but now I would like to cut the branch even further down: by combining many tiny but related commits into one. The best workflow I found (and I don't like it) is to have all those commits on gitlab opened in the Firefox, in the terminal to have opened `git rebase -i` window and picking and combining commits to be squashed together.

Which is quite crazy. What I am dreaming about is to have the `git rebase --interactive` todo list opened in a vim buffer, and then be able to open from inside of this buffer underlying commits in `Gdiff` window, so I can see exactly which files I am picking for squash. This would IMHO hugely improve efficiency of my `git rebase -i` session.

What do you think?

**Comment by tpope** [comment]
I would love this. But how to implement? It see no way to invoke `git rebase` interactive functionality without it invoking an editor, and invoking Vim from inside Vim is not a great use experience.

**Comment by odnoletkov** [comment]
@mcepl I think most of what you described is already possible. With cursor somewhere on the commit hash in the rebase to-do buffer in Vim:
`K` is essentially `git show`
`:Gedit <CTRL-R CTRL-W>` opens fugitive buffer for commit (also see `:Gsplit`/`:Gvsplit`/`:Gtabedit`/`:Gpedit`)

**Comment by rbong** [comment]
You could start a rebase by first setting `$GIT_EDITOR` to `vim -e -u NONE -c "1s/^pick/edit" -c "wq"` and run the rebase with `^` appended onto the target and `--preserve-merges` set so that the first commit is not mangled. You can then edit `.git/rebase-merge/git-rebase-todo` and run `git rebase --continue` when you're ready to proceed.

Setting `GIT_EDITOR` as above causes it so that another instance of vim runs without loading an rc file or starting visual mode. It sets the first commit to edit mode and exits. This is hacky but it at least only relies on vim being available on the system. Despite comments above, from what I can find deleting all lines in the file or setting an invalid `GIT_EDITOR` causes the rebase to abort, although if it works that approach would be preferable.

By appending `^` onto the ref specified in the rebase, it targets the commit before the one specified. You can append as many `^` onto a ref as you want. This is safe in most cases except a root commit. You may check if it is a root commit and handle this special case by just stopping to edit on the root or giving an error. It's not ideal but it's an edge case. `--preserve-merges` needs to be specified, otherwise git will consider editing the initial commit a new change.

So, you are able to start an interactive rebase in edit mode on the commit before the target you want. It would be more ideal to modify the rebase without editing the previous commit, but this is the best way I know to do it. From looking at the shell scripts, it's likely git would need to change to do any better.

@tpope let me know if this approach would be appropriate for a PR. As for a placeholder for anyone who wants this feature, this will get you some nice rebase commands in your `.vimrc`.

```vim
function! g:GitEditTodo(mods) abort
    exec a:mods . ' split ' . fnameescape(fugitive#buffer().repo().dir()) . '/rebase-merge/git-rebase-todo'
endfunction
                                                                                                                       
function! g:GitRebaseInteractive(mods, args) abort
    let l:args = join(a:args[:-2], ' ') . a:args[-1] . '^'
    let l:previous_editor = $GIT_EDITOR
    let $GIT_EDITOR="vim -e -u NONE -c '1s/^pick/edit' -c 'wq'"
    try
        exec 'Git rebase --preserve-merges --interactive ' . l:args
    finally
        let $GIT_EDITOR = l:previous_editor
    endtry
    if !v:shell_error
        call g:GitEditTodo(a:mods)
    endif
endfunction
                                                                                                                       
command! -nargs=+ -complete=customlist,fugitive#Complete Gintrebase :call g:GitRebaseInteractive('<mods>', [<f-args>])
command! -nargs=0 Getodo :call g:GitEditTodo('<mods>')
```

**Comment by rbong** [comment]
You can simply set the editor to `exit 0;` and git will allow you to edit the file yourself. @tpope please let me know if this approach is appropriate for a PR.

Here are some commands for your `.vimrc` for now:

```vim
function! g:GitEditTodo(mods) abort
    exec a:mods . ' split ' . fnameescape(fugitive#buffer().repo().dir()) . '/rebase-merge/git-rebase-todo'
endfunction
                                                                                                                               
function! g:GitRebaseInteractive(mods, args) abort
    let l:previous_editor = $GIT_EDITOR
    let $GIT_EDITOR='exit 0;'
    try
        exec 'Git rebase --interactive ' . a:args
    finally
        let $GIT_EDITOR = l:previous_editor
    endtry
    if !v:shell_error
        call g:GitEditTodo(a:mods)
    endif
endfunction
                                                                                                                               
command! -nargs=+ -complete=customlist,fugitive#Complete Grebaseinteractive :call g:GitRebaseInteractive('<mods>', '<q-args>')
command! -nargs=0 Gedittodo :call g:GitEditTodo('<mods>')
```

**Comment by tpope** [comment]
I could have sworn I tried that without success. Maybe something changed. Good news if so.

The next step would be to make `:wq` in that `git-rebase-todo` buffer actually initiate the rebase. Does `--continue` work for that?

**Comment by rbong** [comment]
@tpope I did some more testing and apparently you cannot just run `--continue`. Other than some internal updating, checking, and error handling that happens automatically when not using internal function calls, this is what `git-core/git-rebase--interactive` runs after editing the TODO file.

**Comment by rbong** [comment]
I did some more testing and apparently, you cannot just run `--continue`. Other than some internal updating, checking, and error handling that happens automatically when not using internal function calls, this is what `git-core/git-rebase--interactive` runs after editing the todo file.

```bash
git checkout "$(git rebase--helper --skip-unnecessary-picks)" || {
    >&2 echo "Could not skip unnecessary pick commands"
    exit 1
}
git rebase--helper --continue (--no-ff)
```

My proposed solution is to run the vim equivalent of the checkout command above, and not run the continue command above, on writing to `.git/rebase-merge/git-rebase-todo` if no `.git/rebase-merge/done` exists. This approach is expanded and explained below.

The `done` file gets created on normal `--interactive` invocation. By running the vim equivalent of the checkout command above if no `done` exists, you could both recover from errors from normal `--interactive` initialization (ex. editing files before finishing editing the todo) by running `:Grebase --edit-todo` and initialize an interactive rebase through `:Grebase --interactive`.

`git rebase--helper --continue` gets passed `--no-ff` through from `git rebase --interactive --no-ff` command. However `rebase--helper --continue` does the same thing as `rebase --continue`. It is better to just check out the appropriate commit and let the user run  `Grebase --continue [--no-ff]` when they're ready. It's a bit of a different interface, but otherwise you sacrifice `--interactive --no-ff` support together. You can of course prompt the user or explain this in the documentation.

Now that this approach is explained I'd like to explore some upsides and downsides that I haven't already covered.

If the user errantly runs `:Grebase --interactive` and then tries to continue the rebase from their shell, it will be no more harmful than a failed normal `--interactive` session and they can just abort the rebase.

The one other downside will be running the internal `rebase--helper` subcommand, which I see you have avoided so far. I don't see much of a way around this. It would be easy to recreate if not for reordering commits (although I would not be surprised if you had more ideas than me to recreate this command).

Let me know your thoughts.

**Comment by rbong** [comment]
I have been experimenting more... there are more considerations, like behaviour on `--continue` when the editor is automatically opened (were you asking about this before or if you could use `--continue` to initiate the rebase normally? I responded thinking you meant the latter above but I can see how you may have meant the former) and opening the todo file normally from the command line without invoking special behaviour. I have also been experimenting with avoiding the use of `rebase--helper` in Vim, and that avenue requires porting over a lot more of the behaviour of `rebase--helper` than I anticipated. We'll either need to settle for using `rebase--helper`, take on a few new large functions, or find a new approach. I'll be sticking with `rebase--helper` for now.

I will probably put up an experimental PR soon just because it will be easier to illustrate the approach I'm taking and discuss it as I take this avenue to its conclusion. I have no pretensions that the branch will get in with all of my own doubts over whether or not this is a good approach, but I think it will get us closer to a real solution, either via determining that a PR must be submitted to git because fugitive shouldn't be doing some of the things in my branch, or real world examples exposed to @tpope 's knowledge in the area.

**Comment by tpope** [comment]
Now that I think about it, couldn't we just write the user edited sequence file to a temp file, and then set the editor to `cp /tmp/file`?

**Comment by rbong** [comment]
That would be, for the most part, a much less hacky approach.

Here's how they generate the list of commits and default commands at the top of the todo file:

```
git rebase--helper --make-script ${keep_empty:+--keep-empty} \
  ${rebase_merges:+--rebase-merges} \
  ${rebase_cousins:+--rebase-cousins} \
  $revisions ${restrict_revision+^$restrict_revision}
```

We would only need to pass through the `git rebase` options (excluding `$restrict_revision`, which seems to be a legacy option) and `$revisions`, which is a range of commits. We could also call it on `--edit-todo` using `.git/rebase-merge/head-name` for the range of commits.

I believe that if we don't want to use internal git helpers we could also use `git log`, which seems to have corresponding options for each rebase option. I don't think that we give up on any error handling with this approach, because there are only errors normally when `--make-script` is empty, so we could just check if the `log` output is empty. I could be wrong.

The comment at the bottom of the todo file is hardcoded and will have to be appended manually no matter what.

After we generate the todo file as described above we can call `git rebase --interactive` and echo any errors or final output to the user.

However, it won't be quite as simple as setting the editor to `cp /tmp/file`. It will have to be something like `if ! commit_started; then cp /tmp/file; else false; fi`. This means that if there is no commit, the user edited todo file will be copied over. Otherwise, the rebase will pause. This will allow us to check for `.git/rebase-merge/amend`, which tells us that we should run `:Gcommit`.

We should take the same approach on `:Grebase --continue`, setting editor to `false` and running `:Gcommit` as needed.

The user will also need to see any output after continuing on intialization or `:Grebase --continue`, as far as I know.

**Comment by tpope** [comment]
So in addition to missing the comments, the output of `--make-script` uses 40 character SHAs rather than abbreviated. I'm also unclear on how to generate `$revisions`. I feel like this probably isn't the best way to go.

I think we should start by focusing exclusively on the `:Grebase --continue` use case, as that's the simplest and it will give us a chance to flesh out how the quickfix list will work along side editor invocation. Then we can move onto `--edit-todo` (which I'm guessing `cp` can probably handle) and then finally the initial `--interactive` mess.

**Comment by rbong** [comment]
I have been experimenting again. There were some recent updates to git. `--make-script` is no longer a publicly accessible command and `git log` does not return the same output, specifically when it comes to parent behaviour and especially rebase label behaviour, so creating the todo file and copying it over will not be trivial.

The `exit 0;` approach is now broken I believe because `rebase --interactive` is no longer a shell script. It was probably a bad idea in the first place.

It's looking more and more like in order to do this without hacks, we'll need to submit a change to git itself. However I do have a PR ready for `--continue` and `--edit-todo`, which I will tie to this issue soon.

**Comment by rbong** [comment]
Workaround for `--interactive` off of my branch:

```vim
function! Grebaseinteractive(args) abort
    let $GIT_EDITOR="sed -ie '0,/pick/ s/pick/edit/'"
    exec 'Git rebase --preserve-merges --interactive' a:args . '^'
    Grebase --edit-todo
endfunction

command! -nargs=+ -complete=customlist,fugitive#Complete Grebaseinteractive :call g:Grebaseinteractive('<q-args>')
```

**Comment by tpope** [comment]
Glad you caught that before we dove any deeper. I was a bit confused reading the source but assumed `git-rebase--preserve-merges.sh` did the heavy lifting.

We could still fall back to the boring dance of running rebase once to copy the sequence file and bail, editing the copy, and then a second rebase to copy the edit back in. I was reluctant to do this because of portability reasons, but after source diving it seems clear we can use a shell script even on Windows. My main annoyance with this approach is `--autostash` churn, but I guess it's still better than nothing.

A clean solution could probably achieved with jobs, but lord, the fact I would have to implement it twice for Vim 8 and Neovim really dampens my motivation there.

**Comment by rbong** [comment]
I didn't think of copying it twice. That would work.

**Comment by rbong** [comment]
With #1139 in, I'm probably *not* going to try my hand at a pull request for `git rebase --interactive` unless if tpope requests help with it. Since it's just copying a file once and then copying it back, most of the complexity lies just with flow control and integrating with the existing code, and tpope has a much greater idea of how everything should work with fugitive.

**Comment by tpope** [comment]
It has occurred to me that we can have the best of both worlds if we prepend `exec false` to the sequence file. Feeling feisty so I've gone ahead and pushed it up. Let me know what problems you spot.

Going forward I think we should move away from using the quickfix list for anything but conflicts, as the abstraction is starting to leak pretty badly.

**Comment by rbong** [comment]
IIRC that will make the behaviour when picking commits in their original order at the beginning of the rebase different because git doesn't know if it can fast-forward past exec commands. I don't know what impact that will have, but I don't think it should be much. Just throwing that out there if you see bugs caused by this.

**Comment by tpope** [comment]
Just tested and it's fast-forwarding fine.

**Comment by mcepl** [comment]
So, what is the conclusion, and how should I do the rebase I mentioned above? Could we get something in ``doc/``?

**Comment by dydokamil** [comment]
hey, not sure how many of you have this problem, but when I first do `:Grebase -i HEAD~2`, then i change the second commit from `pick` to `squash` everything works fine.

But then when another buffer is opened when I type `:Grebase --continue` it asks me to choose messages for these 2 commits, as it normally would, I save the buffer and save it and nothing happens. I am still in the detached head state and have to finish it through terminal :(
