### ISSUE TITLE
Redirection to unexpected directory

### ISSUE THREAD

**Issue by phmarek** [tpope/vim-fugitive#878]
Say that I've got a changed file in my checkout, and I'd like to produce a diff.
```
:Git diff % > some-patch-file.patch
```

But that output will only be in my current directory if the `%` file is in a git checkout that's based at my `$CWD`. If the file is in a submodule, or the editor is at one directory level higher, `fugitive` will `cd` to the checkout directory and make the redirect destination use the wrong target.

Perhaps (at least) the common cases `>`, `&>`, `2>` should be seen and handled? Why is the `cd` needed at all, wouldn't it be better to leave it as-is and only set `$GIT_DIR` correctly?

Thank you for your valuable time.

**Comment by tpope** [comment]
The short answer is that `GIT_DIR`/`--git-dir=` only gets you so far. `:Git diff %` won't work, for example, if your current directory is outside of the project. You could maybe get away with eschewing the `cd` when in a subdirectory, but I would not be surprised if that had other, more subtle, issues.

I think the best workaround is probably to just use `:!git` when you want to keep the current directory, because `:Git` doesn't get you that much else other than the temporary `cd`.

**Comment by phmarek** [comment]
Well, `:!git` doesn't work when the `$PWD` is outside a git repo... `Not a git repository` is the result.

So, the only way to solve that would be to search for the redirection operators, and to make their arguments full paths, right?

Thanks anyway!

**Comment by tpope** [comment]
It is now supported to do `./some-patch-file.patch` to reference a file in the current directory. The bad news is that shell syntax like `>` is no longer supported.
