### ISSUE TITLE
Add step to install vim-rhubarb in installation

### ISSUE THREAD

**Issue by akarki15** [tpope/vim-fugitive#898]
* Now that vim-fugitive has [dependency](https://github.com/tpope/vim-fugitive/blob/26504eecbdb8808618d1d57b8f6cf85ac8c5ad6a/plugin/fugitive.vim#L2381) on vim-rhubarb, lets update the installation to reflect that.
* Without vim-rhubarb installed, some commands in vim-fugitive don't work-
* e.g. :Gbrowse takes us to vim-rhubarb's github page

**Comment by tpope** [comment]
It's no more of a dependency than [fubitive](https://github.com/tommcdo/vim-fubitive) or [fugitive-gitlab](https://github.com/shumphrey/fugitive-gitlab.vim). It only gets special `:Gbrowse` treatment because that behavior used to be integrated, and I wanted to minimize confusion. But GitHub is popular enough that I will add a mention to the README.
