### ISSUE TITLE
:Ggrep --help opens a new file named "usage: git grep [<options>] [-e] <pattern> [<rev>...] [[--] <path>...]"

### ISSUE THREAD

**Issue by Holzhaus** [tpope/vim-fugitive#925]
When using `:Ggrep --help`, Vim will open a new file that is places in the current directory and named `usage: git grep [<options>] [-e] <pattern> [<rev>...] [[--] <path>...]` (string can differ depending on locale).

**Comment by dhruvasagar** [comment]
Ggrep parses the output and builds a quickfix list. By default (check :h :make), it jumps to the first definition and so you see that behavior.

I suggest if you want to use something like `--help` pair it with `:Git grep` instead to see the actual raw output like in a terminal instead of unnecessarily have it parsed into a quickfix list.

**Comment by tpope** [comment]
All wrapper commands now load `--help` into a temp buffer with a `man` file type. Additionally, `:Ggrep` is now smarter about distinguishing between informative output and filenames.
