### ISSUE TITLE
Gblame loses colors

### ISSUE THREAD

**Issue by derenio** [tpope/vim-fugitive#932]
Sometimes `Gblame` loses its colors (and goes back to a white text on a black background; the default `colorscheme`?).
I think that me reloading the `.vimrc` file can be involved in it (`source ~.vimrc` after e.g. definition of a new mapping).

Is there a way to turn the coloring  back?
`Gblame` is the most beloved and often used `fugitive's` feature of mine. I use it almost constantly to navigate through the code and sudden lack of colors really disturbs my flow :/.

Please let me know what logs should I provide the next time (probably soon) I encounter this as to help fixing this bug!

**Comment by tpope** [comment]
My guess is the root of the problem is something in your vimrc that wrecks havoc on reload. You should try stripping it down to see if you can get the problem to go away, and then try to pinpoint the problematic line.

You can possibly work around whatever's happening by one of reloading the file, `:set filetype=fugitiveblame`, or `:set syntax=fugitiveblame`.

**Comment by dhruvasagar** [comment]
Likely this has something to do with one of the plugins meant to deal nicely with large files which may be removing the syntax definitions to make vim experience smoother (large files can cause vim to be sliggish with syntax highlighting)

**Comment by tpope** [comment]
I just switched to using a proper ftdetect file, which I'm going to assume fixes this until I hear otherwise.

**Comment by rperryng** [comment]
This issue was happening for me as well. (`:GBlame` losing color after a vimrc reload)
I found that removing the line, `syntax enable` in my vimrc resolved the issue.
FWIW, I use `vim-plug`, which [automatically executes `syntax enable` for me anyway when I `call plug#end()`](https://github.com/junegunn/vim-plug#usage) anyway.

**Comment by tpope** [comment]
7e91b47021fadef7432856b34167f56569f2ac3f
