### ISSUE TITLE
vim-fugitive breaks CTRL-^ alternate file editing for files named index

### ISSUE THREAD

**Issue by gsauthof** [tpope/vim-fugitive#959]
How to reproduce:

1. go to an empty directory; create 2 text files named index and foo
2. vim index
3. :e foo
4. Ctrl-6 (switches back to index)
5. Ctrl-6 (expected behaviour: switches back to foo, actual behaviour: nothing happens)

I tested with current vim-fugitive on Fedora 26 with a minimal config (i.e. just pathogen and vim-fugitive bundles enabled). When disabling vim-fugitive the alternate file editing works as expected.

Possibly related issue: Autocommands do not fire for files named `index` #834

**Comment by brennen** [comment]
@gsauthof I have a PR in for #834 - see #1196.  It doesn't appear to fix this issue, although I wonder if it might still be a related problem.  I'm not quite sure how `C-^` is implemented under the hood.  Perhaps because the `index` file read happens inside an autocmd using `read <amatch>`, some state is not getting set correctly.

I wonder if some variable could, perhaps, just be set here...

**Comment by tpope** [comment]
I bet `keepalt read` will fix it, if you wanna go for a two-in-one.

**Comment by brennen** [comment]
Sure enough.  Added to PR.
