### ISSUE TITLE
Feature Request: Stage Partial changes by using Selection Mode and then Gwrite on the selection

### ISSUE THREAD

**Issue by danielBingham** [tpope/vim-fugitive#962]
I'd like to be able to stage partial changes by using selection mode to select the changes I'd like to stage and then entering ``:Gwrite`` once the selection is highlighted.  This would allow me to precisely control my commits and commit changes in logical batches with out having to break my work flow to commit the changes at each stage.

**Comment by sunnypp** [comment]
It would be nice to have this feature in Fugitive!

By the way, while [vim-gitgutter](https://github.com/airblade/vim-gitgutter) doesn't allow "selected lines to commit", at least I can do a Hunk instead of the whole file.  Currently I am using it to show signs in my editor regarding the file's status under Git.  When I've finished coding and feel like I need to commit, I would do `[c` `]c` to navigate between Hunks and do`<leader>hs` to stage separated hunks into 1 commit. (With our beloved `:Gcommit`)

There is also an issue created for vim-gitgutter asking for staging only selected added lines in visual mode.  Not a priority of the author though...

Hope this may help you for the moment being :)

**Comment by airblade** [comment]
> There is also an issue created for vim-gitgutter asking for staging only selected added lines in visual mode.

@sunnypp You can do this now :) https://github.com/airblade/vim-gitgutter/commit/bc1d28db46f7d8f174df4b0c98da092e10369281

**Comment by tpope** [comment]
This is #269.
