### ISSUE TITLE
Crashes Vim 8.x on start up on OS 10.9.5

### ISSUE THREAD

**Issue by srustamo** [tpope/vim-fugitive#979]
I was seeing Vim crash on startup, when opening OS associated files with Vim from Finder (clicking on it, nothing fancy).
Removing plugins one by one, narrowed the crash down to vim-fugitive.
I noticed that crash mostly happens when a dir is git controlled.
Is there options to delay the loading of this plugin after Vim opens the file, perhaps?

My config is [here](https://github.com/srustamo/dotfiles/tree/master/vim).
 
Minimal plugins without crash (adding to this list vim-fugitive starts crashing Vim on startup): 
ctrlp.vim
nerdtree
tmuxline.vim
vim-airline
vim-airline-themes
vim-colors-solarized

All plugins:
undoquit.vim
vim-commentary
vim-fugitive
vim-gitgutter
vim-minimap
vim-unimpaired
vim-vinegar
ctrlp.vim
nerdtree
tmuxline.vim
vim-airline
vim-airline-themes
vim-colors-solarized

**Comment by tpope** [comment]
If it's crashing Vim I'd call it a Vim bug. We have an autoload file so that may fix it by way of "loading the plugin after Vim opens the file." If not, I'm happy to offer further suggestions if you can figure out a more precise culprit (by deleting half the plugin and seeing if the crash happens, for example.)
